# add_subdirectory(units/aca-full-matrix-approximation)
# add_subdirectory(units/aca-random-select-ref-row)
add_subdirectory(units/binary-tree-copy)
add_subdirectory(units/binary-tree-get-leaves)
add_subdirectory(units/binary-tree)
add_subdirectory(units/block-cluster-tree-copy-constructor)
add_subdirectory(units/block-cluster-tree-extend-finer-than-partition)
add_subdirectory(units/block-cluster-tree-extend-to-finer-partition)
add_subdirectory(units/block-cluster-tree-hp-coarse-non-tensor-product)
add_subdirectory(units/block-cluster-tree-hp-fine-non-tensor-product)
add_subdirectory(units/block-cluster-tree-hp)
add_subdirectory(units/block-cluster-tree-overloaded-assignment)
add_subdirectory(units/block-cluster-tree-subtree)
add_subdirectory(units/block-cluster-tree-visualize-with-rank)
add_subdirectory(units/block-cluster-tree)
# add_subdirectory(units/cell-distance)
# add_subdirectory(units/cell-neighboring-type-for-surface-mesh)
# add_subdirectory(units/cell-neighboring-type)
# add_subdirectory(units/cluster-diameter)
# add_subdirectory(units/cluster-set-inclusion)
add_subdirectory(units/cluster-tree-copy-constructor)
# add_subdirectory(units/cu-bem-values)
# add_subdirectory(units/cu-qgauss-copy-from-host)
# add_subdirectory(units/cu-scratch-data)
add_subdirectory(units/cudafullmatrix-det2x2)
add_subdirectory(units/cudafullmatrix-det3x3)
# add_subdirectory(units/cudafullmatrix-invert-by-gauss-elim)
# add_subdirectory(units/cudafullmatrix-invert2x2)
# add_subdirectory(units/cudafullmatrix-mmult)
# add_subdirectory(units/cudafullmatrix-vmult)
# add_subdirectory(units/dealii-vector-argmax-argmin)
# add_subdirectory(units/detect-cell-neighboring-type-for-different-triangulations)
# add_subdirectory(units/detect-cell-neighboring-type-for-same-dofhandlers)
# add_subdirectory(units/detect-cell-neighboring-type-for-same-triangulations)
# add_subdirectory(units/dof-forward-and-backward-permutation)
# add_subdirectory(units/dof-to-cell-topology)
# add_subdirectory(units/fullmatrix-hmatrix-mmult)
# add_subdirectory(units/gauss-legendre-quad-4d)
# add_subdirectory(units/get-vertex-dof-indices)
# add_subdirectory(units/get_dofs_per_face_for_fe)
# add_subdirectory(units/get_support_points_in_real_cell)
# add_subdirectory(units/get_unit_support_points)
# add_subdirectory(units/get_vertices_in_real_cell)
# add_subdirectory(units/get_vertices_in_unit_cell)
# add_subdirectory(units/gmsh-and-dealii-node-ordering)
# add_subdirectory(units/hmatrix-add-formatted-with-factor)
# add_subdirectory(units/hmatrix-add-formatted)
# add_subdirectory(units/hmatrix-add-rkmatrix-into-new-hmatrix-with-factor)
# add_subdirectory(units/hmatrix-add-rkmatrix-into-new-hmatrix)
# add_subdirectory(units/hmatrix-add-rkmatrix-with-factor)
# add_subdirectory(units/hmatrix-add-rkmatrix)
add_subdirectory(units/hmatrix-backward-substitution-coarse-ntp)
add_subdirectory(units/hmatrix-backward-substitution-unit-diag)
add_subdirectory(units/hmatrix-backward-substitution)
# add_subdirectory(units/hmatrix-bct-struct-with-rank)
# add_subdirectory(units/hmatrix-block-triangular-backward-substitution-unit-diag)
# add_subdirectory(units/hmatrix-block-triangular-backward-substitution)
# add_subdirectory(units/hmatrix-block-triangular-forward-substitution-unit-diag)
# add_subdirectory(units/hmatrix-block-triangular-forward-substitution)
# add_subdirectory(units/hmatrix-check-parent-and-submatrix-index)
# add_subdirectory(units/hmatrix-cholesky-backward-substitution)
# add_subdirectory(units/hmatrix-coarsening)
# add_subdirectory(units/hmatrix-deep-copy-constructor)
# add_subdirectory(units/hmatrix-find-diagonal-blocks)
# add_subdirectory(units/hmatrix-fine-ntp-to-tp)
add_subdirectory(units/hmatrix-forward-substitution-coarse-ntp)
add_subdirectory(units/hmatrix-forward-substitution-matrix-valued)
add_subdirectory(units/hmatrix-forward-substitution-unit-diag)
add_subdirectory(units/hmatrix-forward-substitution)
# add_subdirectory(units/hmatrix-fullmatrix-conversion)
# add_subdirectory(units/hmatrix-fullmatrix-mmult)
# add_subdirectory(units/hmatrix-hmatrix-alpha-mmult-level-conserving-all-fine-ntp-member-function-call)
# add_subdirectory(units/hmatrix-hmatrix-mmult-all-coarse-ntp)
# add_subdirectory(units/hmatrix-hmatrix-mmult-all-fine-ntp-with-adding)
# add_subdirectory(units/hmatrix-hmatrix-mmult-all-fine-ntp)
# add_subdirectory(units/hmatrix-hmatrix-mmult-coarse-coarse-fine-ntp)
# add_subdirectory(units/hmatrix-hmatrix-mmult-coarse-fine-coarse-ntp)
# add_subdirectory(units/hmatrix-hmatrix-mmult-fine-coarse-fine-ntp)
# add_subdirectory(units/hmatrix-hmatrix-mmult-fine-fine-coarse-ntp)
# add_subdirectory(units/hmatrix-hmatrix-mmult-level-conserving-all-coarse-ntp)
# add_subdirectory(units/hmatrix-hmatrix-mmult-level-conserving-all-fine-ntp-member-function-call)
# add_subdirectory(units/hmatrix-hmatrix-mmult-level-conserving-all-fine-ntp)
# add_subdirectory(units/hmatrix-hmatrix-mmult-level-conserving-coarse-coarse-fine-ntp)
# add_subdirectory(units/hmatrix-hmatrix-mmult-level-conserving-coarse-fine-coarse-ntp)
# add_subdirectory(units/hmatrix-hmatrix-mmult-level-conserving-fine-coarse-fine-ntp)
# add_subdirectory(units/hmatrix-hmatrix-mmult-level-conserving-fine-fine-coarse-ntp)
# add_subdirectory(units/hmatrix-invert-by-gauss-elim)
add_subdirectory(units/hmatrix-memory-consumption)
# add_subdirectory(units/hmatrix-overloaded-deep-assignment)
# add_subdirectory(units/hmatrix-overloaded-shallow-assignment)
# add_subdirectory(units/hmatrix-refinement)
# add_subdirectory(units/hmatrix-rkmatrix-conversion)
# add_subdirectory(units/hmatrix-rkmatrix-mmult)
# add_subdirectory(units/hmatrix-set-block-type)
# add_subdirectory(units/hmatrix-set-property)
# add_subdirectory(units/hmatrix-shallow-copy-constructor)
add_subdirectory(units/hmatrix-solve-cholesky)
add_subdirectory(units/hmatrix-solve-lu)
add_subdirectory(units/hmatrix-symm-vmult-symm)
add_subdirectory(units/hmatrix-transpose-forward-substitution-matrix-valued)
# add_subdirectory(units/hmatrix-transpose-forward-substitution)
# add_subdirectory(units/hmatrix-truncate-to-fixed-rank-preserve-spd)
# add_subdirectory(units/hmatrix-truncate-to-fixed-rank)
add_subdirectory(units/hmatrix-tvmult-symm)
add_subdirectory(units/hmatrix-tvmult-tril)
add_subdirectory(units/hmatrix-tvmult)
add_subdirectory(units/hmatrix-vmult-symm)
add_subdirectory(units/hmatrix-vmult-tril)
add_subdirectory(units/hmatrix-vmult)
add_subdirectory(units/hmatrix-write-leaf-set-by-iteration)
# add_subdirectory(units/hp-matrix)
add_subdirectory(units/lapack-matrix-add-with-factor)
add_subdirectory(units/lapack-matrix-add-without-factor)
# add_subdirectory(units/lapack-matrix-agglomeration-of-two-submatrices)
# add_subdirectory(units/lapack-matrix-agglomeration)
# add_subdirectory(units/lapack-matrix-backward-substitution)
# add_subdirectory(units/lapack-matrix-delete-rows-and-columns)
# add_subdirectory(units/lapack-matrix-fill-rows)
# add_subdirectory(units/lapack-matrix-fill)
# add_subdirectory(units/lapack-matrix-forward-substitution)
# add_subdirectory(units/lapack-matrix-global-to-rkmatrix)
# add_subdirectory(units/lapack-matrix-global-to-submatrix)
# add_subdirectory(units/lapack-matrix-hstack-vstack)
# add_subdirectory(units/lapack-matrix-init-with-zeros)
# add_subdirectory(units/lapack-matrix-inverse)
# add_subdirectory(units/lapack-matrix-local-to-rkmatrix)
# add_subdirectory(units/lapack-matrix-local-to-submatrix)
add_subdirectory(units/lapack-matrix-memory-consumption)
# add_subdirectory(units/lapack-matrix-mmult)
# add_subdirectory(units/lapack-matrix-qr)
# add_subdirectory(units/lapack-matrix-rank-k-decompose)
# add_subdirectory(units/lapack-matrix-read-from-mat)
# add_subdirectory(units/lapack-matrix-reduced-svd-degenerate-cases)
# add_subdirectory(units/lapack-matrix-reduced-svd)
# add_subdirectory(units/lapack-matrix-scale-matrix)
# add_subdirectory(units/lapack-matrix-scale-rows-and-columns)
# add_subdirectory(units/lapack-matrix-solve-by-cholesky)
# add_subdirectory(units/lapack-matrix-solve-by-lu)
# add_subdirectory(units/lapack-matrix-svd-degenerate-cases)
# add_subdirectory(units/lapack-matrix-svd-rank)
# add_subdirectory(units/lapack-matrix-svd)
# add_subdirectory(units/lapack-matrix-transpose)
# add_subdirectory(units/lapack-matrix-tvmult)
# add_subdirectory(units/lapack-matrix-vmult)
# add_subdirectory(units/normal-vector)
# add_subdirectory(units/octave-read-vector)
# add_subdirectory(units/planarity-of-gmsh-quad-cell)
# add_subdirectory(units/point-4d)
# add_subdirectory(units/raw-lapack-ctrsv)
# add_subdirectory(units/raw-lapack-dtrsv)
# add_subdirectory(units/raw-lapack-strsv)
# add_subdirectory(units/raw-lapack-ztrsv)
# add_subdirectory(units/regex-file-basename-and-ext)
# add_subdirectory(units/rkmatrix-add-formatted-using-qr-with-factor)
# add_subdirectory(units/rkmatrix-add-formatted-using-qr)
# add_subdirectory(units/rkmatrix-add-formatted-with-factor)
# add_subdirectory(units/rkmatrix-add-formatted)
# add_subdirectory(units/rkmatrix-agglomeration-2nd-block-rank0)
# add_subdirectory(units/rkmatrix-agglomeration-3rd-block-rank0)
# add_subdirectory(units/rkmatrix-agglomeration-4th-block-rank0)
# add_subdirectory(units/rkmatrix-agglomeration-interwoven-indices-2nd-block-rank0)
# add_subdirectory(units/rkmatrix-agglomeration-interwoven-indices-3rd-block-rank0)
# add_subdirectory(units/rkmatrix-agglomeration-interwoven-indices-4th-block-rank0)
# add_subdirectory(units/rkmatrix-agglomeration-interwoven-indices-rank0)
# add_subdirectory(units/rkmatrix-agglomeration-interwoven-indices)
# add_subdirectory(units/rkmatrix-agglomeration-of-two-submatrices-interwoven-indices-rank0)
# add_subdirectory(units/rkmatrix-agglomeration-of-two-submatrices-interwoven-indices)
# add_subdirectory(units/rkmatrix-agglomeration-of-two-submatrices-rank0)
# add_subdirectory(units/rkmatrix-agglomeration-of-two-submatrices)
# add_subdirectory(units/rkmatrix-agglomeration-rank0)
# add_subdirectory(units/rkmatrix-agglomeration)
# add_subdirectory(units/rkmatrix-assemble-from-rkmatrix)
# add_subdirectory(units/rkmatrix-frobenius-norm)
# add_subdirectory(units/rkmatrix-global-to-rkmatrix)
# add_subdirectory(units/rkmatrix-global-to-submatrix)
# add_subdirectory(units/rkmatrix-hmatrix-mmult)
# add_subdirectory(units/rkmatrix-local-to-rkmatrix)
# add_subdirectory(units/rkmatrix-local-to-submatrix)
add_subdirectory(units/rkmatrix-memory-consumption)
# add_subdirectory(units/rkmatrix-to-fullmatrix-rank0)
# add_subdirectory(units/rkmatrix-truncate-to-rank-with-error-matrices)
# add_subdirectory(units/rkmatrix-truncate-to-rank)
add_subdirectory(units/sauter-quad-common-edge)
add_subdirectory(units/sauter-quad-common-vertex)
add_subdirectory(units/sauter-quad-regular)
add_subdirectory(units/sauter-quad-same-panel)
add_subdirectory(units/simple-bounding-box)
# add_subdirectory(units/stl-gen-linear-indices)
# add_subdirectory(units/stl-memory-consumption-of-map)
# add_subdirectory(units/surface-jacobian-det)
# add_subdirectory(units/verify-cell-iters-in-dofhandler-and-triangulation)
# add_subdirectory(units/verify-copy-dealii-function-object)
# add_subdirectory(units/verify-copy-vector)
# add_subdirectory(units/verify-cross-product-of-tensors)
# add_subdirectory(units/verify-cu-table)
# add_subdirectory(units/verify-dealii-vector-init-with-zeros)
# add_subdirectory(units/verify-dealii-vector-memory)
# add_subdirectory(units/verify-dof-support-points)
# add_subdirectory(units/verify-fe-info)
# add_subdirectory(units/verify-fe_q-dof-numbering)
# add_subdirectory(units/verify-fullmatrix-major)
# add_subdirectory(units/verify-get-dpo-vector)
# add_subdirectory(units/verify-get-vertex-indices-via-face-iter)
# add_subdirectory(units/verify-integration-on-sphere-manifold)
# add_subdirectory(units/verify-jxw-on-fe_q-fe_dgq)
# add_subdirectory(units/verify-mapping-q-generic)
# add_subdirectory(units/verify-memory-continuity-for-point-table)
# add_subdirectory(units/verify-memory-continuity-for-tensor-table)
# add_subdirectory(units/verify-ndarray-indices)
# add_subdirectory(units/verify-qgauss4-data-configuration)
add_subdirectory(units/verify-sauter-quad-parametric-transform-common-edge)
add_subdirectory(units/verify-sauter-quad-parametric-transform-common-vertex)
add_subdirectory(units/verify-sauter-quad-parametric-transform-same-panel)
# add_subdirectory(units/verify-scalar-product-of-tensors)
# add_subdirectory(units/verify-surface-mesh-refined-with-volume-mesh)
# add_subdirectory(units/verify-surface-mesh-vertex-indices)
# add_subdirectory(units/verify-table-copy-constructor)
# add_subdirectory(units/verify-two-dofhandlers-on-a-same-triangulation)
# add_subdirectory(units/verify-two-surface-mesh-vertex-indices)
# add_subdirectory(units/verify-vertex-order-in-cell-and-fe-support-points)
# add_subdirectory(units/verify-vertex-order-in-cell-and-mapping-support-points)
add_subdirectory(functions/laplace-bem/dirichlet-full-matrix)
add_subdirectory(functions/laplace-bem/dirichlet-hmatrix-two-spheres)
add_subdirectory(functions/laplace-bem/dirichlet-hmatrix)
add_subdirectory(functions/laplace-bem/mixed-hmatrix)
add_subdirectory(functions/laplace-bem/neumann-full-matrix)
add_subdirectory(functions/laplace-bem/neumann-hmatrix)
add_subdirectory(units/determinant4x4)
# add_subdirectory(units/verify-integration-on-cad-surface)
add_subdirectory(units/verify-integration-on-cylinder-hull)
add_subdirectory(units/hbem-octave-wrapper)
add_subdirectory(demos/call-octave-catch2)
add_subdirectory(demos/call-octave-dealii)
add_subdirectory(units/verify-deterministic-random-numbers)
add_subdirectory(functions/laplace-bem/mixed-l-shape)
add_subdirectory(baseline/laplace-bem/dirichlet-full-matrix-single-thread)
add_subdirectory(baseline/laplace-bem/mixed-spanner)
add_subdirectory(units/cudafullmatrix-Tmmult)
add_subdirectory(units/cudafullmatrix-Tvmult)
add_subdirectory(units/cudafullmatrix-mTmult)
add_subdirectory(units/hmatrix-hmatrix-Tmmult-level-conserving-all-coarse-ntp)
add_subdirectory(units/hmatrix-hmatrix-Tmmult-level-conserving-all-fine-ntp)
add_subdirectory(units/hmatrix-hmatrix-Tmmult-level-conserving-coarse-coarse-fine-ntp)
add_subdirectory(units/hmatrix-hmatrix-Tmmult-level-conserving-coarse-fine-coarse-ntp)
add_subdirectory(units/hmatrix-hmatrix-Tmmult-level-conserving-fine-coarse-fine-ntp)
add_subdirectory(units/hmatrix-hmatrix-Tmmult-level-conserving-fine-fine-coarse-ntp)
add_subdirectory(units/hmatrix-hmatrix-Tmmult-level-conserving-symm-result-ntp)
add_subdirectory(units/hmatrix-hmatrix-mTmult-level-conserving-all-coarse-ntp)
add_subdirectory(units/hmatrix-hmatrix-mTmult-level-conserving-all-fine-ntp)
add_subdirectory(units/hmatrix-hmatrix-mTmult-level-conserving-coarse-coarse-fine-ntp)
add_subdirectory(units/hmatrix-hmatrix-mTmult-level-conserving-coarse-fine-coarse-ntp)
add_subdirectory(units/hmatrix-hmatrix-mTmult-level-conserving-fine-coarse-fine-ntp)
add_subdirectory(units/hmatrix-hmatrix-mTmult-level-conserving-fine-fine-coarse-ntp)
add_subdirectory(units/hmatrix-hmatrix-mTmult-level-conserving-symm-result)
add_subdirectory(units/hmatrix-link-nodes-on-same-levels)
add_subdirectory(units/hbem-octave-wrapper-matrix-value)
add_subdirectory(units/hmatrix-link-nodes-on-cross-from-diagonal-blocks)
add_subdirectory(units/cluster-tree-hp)
add_subdirectory(units/cluster-tree)
add_subdirectory(units/point-4d)
add_subdirectory(units/quad-tree-copy)
add_subdirectory(units/quad-tree-get-leaves)
add_subdirectory(units/quad-tree)
add_subdirectory(units/rkmatrix-vmult)
add_subdirectory(units/hmatrix-solve-lu-task-parallel)
add_subdirectory(baseline/hmatrix/lu-factorization-serial)
add_subdirectory(baseline/hmatrix/lu-factorization-task-parallel)
add_subdirectory(units/hmatrix-symmetric-link-nodes-on-same-levels)
add_subdirectory(units/hmatrix-symmetric-link-nodes-on-cross-from-diagonal-blocks)
add_subdirectory(units/hmatrix-cholesky-transpose-forward-substitution-matrix-valued)
add_subdirectory(units/hmatrix-solve-cholesky-task-parallel)
add_subdirectory(baseline/hmatrix/cholesky-factorization-serial)
add_subdirectory(baseline/hmatrix/cholesky-factorization-task-parallel)
add_subdirectory(baseline/laplace-bem/dirichlet-hmatrix-two-spheres)
add_subdirectory(baseline/laplace-bem/dirichlet-hmatrix)
add_subdirectory(baseline/laplace-bem/neumann-hmatrix)
add_subdirectory(regressions/cholesky-factorization-task-parallel)
add_subdirectory(regressions/lu-factorization-task-parallel)
add_subdirectory(units/dealii-full-matrix-size)
add_subdirectory(units/lapack-matrix-keep-first-n-columns)
add_subdirectory(units/verify-dealii-memory-consumption)
add_subdirectory(units/binary-tree-memory-consumption)
add_subdirectory(units/hmatrix-hmatrix-alpha-mTmult-level-conserving-all-fine-ntp-member-function-call)
add_subdirectory(units/quad-tree-memory-consumption)
add_subdirectory(baseline/hmatrix/hmatrix-related-memory-consumption)
add_subdirectory(units/sequence_partition/verify-algorithm)
add_subdirectory(baseline/sequence-partition)
add_subdirectory(units/hmatrix-write-leaf-set-by-iteration-hilbert-curve)
add_subdirectory(units/hmatrix-symm-write-leaf-set-by-iteration-hilbert-curve)
add_subdirectory(units/hmatrix-symm-write-leaf-set-by-iteration)
add_subdirectory(units/hmatrix-lower-write-leaf-set-by-iteration-hilbert-curve)
add_subdirectory(units/hmatrix-lower-write-leaf-set-by-iteration)
add_subdirectory(units/hmatrix-upper-write-leaf-set-by-iteration-hilbert-curve)
add_subdirectory(units/hmatrix-upper-write-leaf-set-by-iteration)
add_subdirectory(units/hmatrix-leaf-set-vmult-or-tvmult-task-costs)
add_subdirectory(units/hmatrix-vmult-parallel)
add_subdirectory(units/hmatrix-vmult-symm-parallel)
add_subdirectory(units/hmatrix-vmult-tril-parallel)
add_subdirectory(units/hmatrix-tvmult-parallel)
add_subdirectory(units/hmatrix-tvmult-symm-parallel)
add_subdirectory(units/hmatrix-tvmult-tril-parallel)
add_subdirectory(units/hmatrix-vmult-triu)
add_subdirectory(units/hmatrix-tvmult-triu)
add_subdirectory(units/hmatrix-tvmult-triu-parallel)
add_subdirectory(units/hmatrix-vmult-triu-parallel)
add_subdirectory(baseline/hmatrix/vmult-parallel)
add_subdirectory(units/hmatrix-vmult-serial-iterative)
add_subdirectory(units/hmatrix-vmult-symm-serial-iterative)
add_subdirectory(units/hmatrix-vmult-tril-serial-iterative)
add_subdirectory(units/hmatrix-vmult-triu-serial-iterative)
add_subdirectory(units/hmatrix-tvmult-serial-iterative)
add_subdirectory(units/hmatrix-tvmult-symm-serial-iterative)
add_subdirectory(units/hmatrix-tvmult-tril-serial-iterative)
add_subdirectory(units/hmatrix-tvmult-triu-serial-iterative)
add_subdirectory(units/assign-entity-tag-to-cell)
add_subdirectory(units/build-volume-to-surface-topology)
add_subdirectory(baseline/hmatrix/vmult-serial-iterative)
add_subdirectory(baseline/hmatrix/vmult-serial-recursive)
add_subdirectory(demos/fmt-output)
add_subdirectory(demos/reflectcpp-usage)
add_subdirectory(units/build-surface-to-line-topology)
add_subdirectory(units/read-1d-skeleton-mesh)
add_subdirectory(units/create-efield-subdomains)
add_subdirectory(units/create-efield-subdomain-hmatrices)
add_subdirectory(units/occ-nurbs-manifold)
add_subdirectory(units/verify-dealii-dof-on-multigrid)
add_subdirectory(units/op-precond-coupling-matrix-for-dirichlet)
add_subdirectory(units/op-precond-averaging-matrix-for-dirichlet)
add_subdirectory(units/op-precond-mass-matrix-for-dirichlet)
add_subdirectory(units/op-precond-hmatrix-for-dirichlet)
add_subdirectory(units/verify-dealii-read-msh-and-refine-global)
add_subdirectory(units/verify-gmsh-cell-indices-in-refined-mesh)
add_subdirectory(functions/laplace-bem/dirichlet-hmatrix-op-precond)
add_subdirectory(demos/template-pimpl)
add_subdirectory(functions/laplace-bem/neumann-hmatrix-op-precond)
add_subdirectory(units/verify-dealii-traverse-cell-iterators-in-two-dofhandlers)
add_subdirectory(units/op-precond-averaging-matrix-for-neumann)
add_subdirectory(units/op-precond-coupling-matrix-for-neumann)
add_subdirectory(functions/laplace-bem/dirichlet-hmatrix-two-spheres-op-precond)
