#ifndef HIERBEM_SRC_HBEM_LAPLACE_CU_RELATED_H
#define HIERBEM_SRC_HBEM_LAPLACE_CU_RELATED_H

#include "config.h"

HBEM_NS_OPEN

void
initCudaRuntime();

HBEM_NS_CLOSE

#endif // HIERBEM_SRC_HBEM_LAPLACE_CU_RELATED_H
