// Copyright (C) 2025 Xiaozhe Wang <chaoslawful@gmail.com>
//
// This file is part of the HierBEM library.
//
// HierBEM is free software: you can use it, redistribute it and/or modify it
// under the terms of the GNU Lesser General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version. The full text of the license can be found in the
// file LICENSE at the top level directory of HierBEM.

/**
 * HierBEM real valued Laplace solver workbench
 */

#include <deal.II/base/logstream.h>
#include <deal.II/base/timer.h>

#include <deal.II/grid/grid_in.h>

#include <cpptrace/from_current.hpp>
#include <fmt/core.h>

#include <filesystem>
#include <fstream>
#include <iostream>
#include <memory>
#include <system_error>

#include "bem/types.h"
#include "config_file/config_file.h"
#include "config_file/config_structs.h"
#include "config_file/cu_related.h"
#include "grid/grid_in_ext.h"
#include "laplace/laplace_bem.h"
#include "utilities/debug_tools.h"

using namespace dealii;
using namespace HierBEM;

class LaplaceWorkbench
{
public:
  using SolverType = LaplaceBEM<2, 3, double, double>;
  using TriaType   = Triangulation<3>;
  using GridInType = GridIn<3>;

  static constexpr const char *LOG_PREFIX       = "HierBEM";
  static constexpr const char *RUNTIME_LOG_FILE = "hierbem_laplace.log";

  LaplaceWorkbench()
    : log_file_os_()
    , bem_(nullptr)
  {}

  void
  initWorkDir()
  {
    const auto &conf_inst  = ConfigFile::instance().getConfig();
    const auto &output_dir = conf_inst.project.output_dir;
    const auto &proj_name  = conf_inst.project.project_name.value();
    const auto &work_dir   = std::filesystem::path(output_dir) / proj_name;

    // Create working directory if it doesn't exist
    std::error_code ec;
    std::filesystem::create_directories(work_dir, ec);
    if (ec)
      {
        throw fmt::system_error(ec.value(),
                                "Failed to create working directory: {}",
                                work_dir.string());
      }

    // Change current working directory to the project directory
    std::filesystem::current_path(work_dir);
  }

  void
  initLogger()
  {
    // Write run-time logs to file
    log_file_os_ = std::make_shared<std::ofstream>(RUNTIME_LOG_FILE);

    deallog.pop();
    deallog.depth_console(0);
    deallog.depth_file(5);
    deallog.attach(*log_file_os_);
  }

  void
  initRuntime(const ConfParallelization &parallel_params)
  {
    initCudaRuntime(parallel_params);
  }

  void
  setupHierBEMSolver()
  {
    const auto &conf_inst = ConfigFile::instance().getConfig();

    // Initialize HierBEM Laplace solver
    bem_ = std::make_unique<SolverType>(
      ConfLaplaceBEM{conf_inst.bem.fe_order_for_dirichlet_space,
                     conf_inst.bem.fe_order_for_neumann_space,
                     problemTypeLiteralToEnum(conf_inst.bem.problem_type),
                     conf_inst.bem.is_interior_problem},
      conf_inst.hmatrix,
      conf_inst.hmatrix_precond,
      conf_inst.sauter_quad,
      conf_inst.sauter_quad_precond,
      conf_inst.linear_solver,
      conf_inst.op_precond,
      conf_inst.parallel);

    // Set project name
    bem_->set_project_name(conf_inst.project.project_name.value());
  }

  void
  setupMeshAndManifold()
  {
    // Load mesh file
    const auto   &conf_inst = ConfigFile::instance().getConfig();
    std::ifstream mesh_file(conf_inst.project.mesh_file);
    read_msh(mesh_file, bem_->get_triangulation());

    // Reconstruct boundary-volume entity relationship if the CAD file is given.
    // Otherwise, we assume the model is generated by deal.ii which has only one
    // domain.
    if (!conf_inst.project.cad_file.empty())
      {
        bem_->get_subdomain_topology().generate_topology(
          conf_inst.project.cad_file, conf_inst.project.mesh_file);
      }
    else
      {
        bem_->get_subdomain_topology()
          .generate_single_domain_topology_for_dealii_model({0});
      }
  }

  void
  setupBoundaryConds()
  {
    // TBD
  }

  void
  runSolverAndOutput()
  {
    bem_->run();
  }

  void
  startup()
  {
    initWorkDir(); // Make working directory hierarchies if it doesn't
                   // exist
    initLogger();  // Initialize deal.ii logger
    LogStream::Prefix prefix_string(LOG_PREFIX);

    initRuntime(ConfigFile::instance()
                  .getConfig()
                  .parallel); // Initialize OpenBLAS/CUDA runtimes

    Timer timer; // Create and start the timer

    setupHierBEMSolver(); // Prepare HierBEM Laplace solver
    timer.stop();
    print_wall_time(deallog, timer, "program preparation");

    timer.start();
    setupMeshAndManifold(); // Read in mesh and assign manifolds if any
    timer.stop();
    print_wall_time(deallog, timer, "read mesh");

    timer.start();
    setupBoundaryConds(); // Setup boundary conditions if any
    timer.stop();
    print_wall_time(deallog, timer, "assign boundary conditions");

    timer.start();
    runSolverAndOutput(); // Assemble and solve BEM system, output
                          // results
    timer.stop();
    print_wall_time(deallog, timer, "run the solver");

    // Final summary log
    deallog << "Program exits with a total wall time " << timer.wall_time()
            << "s" << std::endl;
    bem_->print_memory_consumption_table(deallog.get_file_stream());
  }

protected:
  ProblemType
  problemTypeLiteralToEnum(const ProblemTypeLiteral &literal)
  {
    switch (literal.value())
      {
        case ProblemTypeLiteral::value_of<"neumann">():
          return ProblemType::NeumannBCProblem;
        case ProblemTypeLiteral::value_of<"dirichlet">():
          return ProblemType::DirichletBCProblem;
        case ProblemTypeLiteral::value_of<"mixed">():
          return ProblemType::MixedBCProblem;
        default:
          throw std::runtime_error("Unknown problem type");
      }
  }

  std::shared_ptr<std::ofstream> log_file_os_;
  std::unique_ptr<SolverType>    bem_;
};



int
main(int argc, char **argv)
{
  CPPTRACE_TRY
  {
    if (argc != 2)
      {
        std::cerr << "Usage: " << argv[0] << " <config file>" << std::endl;
        return 1;
      }

    ConfigFile::instance().initialize(argv[1]); // Load configuration file

    LaplaceWorkbench workbench;
    workbench.startup();

    return 0;
  }
  CPPTRACE_CATCH(const std::exception &e)
  {
    std::cerr << "Exception: " << e.what() << std::endl;
    cpptrace::from_current_exception().print();
    return 1;
  }
}
