laplace-bem: /home/jihuan/Projects/deal.ii/program/dealii-9.1.1/examples/laplace-bem/tests/block-cluster-tree-extend-finer-than-partition/bct-extend-finer-than-partition.cc File Reference
bct-extend-finer-than-partition.cc File Reference
Verify extend a block cluster tree to be finer than a given partition.
#include <fstream>
#include <iostream>
#include "block_cluster_tree.h"
Functions
int main ()
Detailed Description
Verify extend a block cluster tree to be finer than a given partition.
Author
Jihuan Tian
Date
2021-07-22
Function Documentation
main()
int main ()
Set the dimension of the H^p-matrix to be built.
Set the minimum cluster size.
Generate the cluster tree using cardinality based partition.
Create two block cluster trees. One has the fine non-tensor product, and the other has the coarse non-tensor product partition.
Make a copy of the first tree then extend it.
References BlockClusterTree< spacedim, Number >::extend_finer_than_partition(), BlockClusterTree< spacedim, Number >::get_leaf_set(), ClusterTree< spacedim, Number >::partition(), BlockClusterTree< spacedim, Number >::partition_coarse_non_tensor_product(), BlockClusterTree< spacedim, Number >::partition_fine_non_tensor_product(), and BlockClusterTree< spacedim, Number >::write_leaf_set().