laplace-bem: /home/jihuan/Projects/deal.ii/program/dealii-9.1.1/examples/laplace-bem/tests/block-cluster-tree/block-cluster-tree.cc File Reference
block-cluster-tree.cc File Reference
Hierarchical matrices
This files verifies the admissible block cluster partition.
#include <deal.II/base/logstream.h>
#include <deal.II/base/point.h>
#include <deal.II/fe/fe_q.h>
#include <deal.II/fe/mapping_q_generic.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_in.h>
#include <deal.II/grid/grid_out.h>
#include <deal.II/lac/full_matrix.h>
#include <deal.II/lac/vector.h>
#include <deal.II/numerics/data_out.h>
#include <simple_bounding_box.h>
#include <fstream>
#include "block_cluster_tree.h"
#include "cluster_tree.h"
#include "debug_tools.h"
Functions
int main ()
Detailed Description
This files verifies the admissible block cluster partition.
Date
2021-04-28
Author
Jihuan Tian
Function Documentation
main()
int main ()
Initialize deal.ii log stream.
Generate the 3x3 grid in a 2D square.
Save the mesh to a file for visualization.
Read the mesh from a file.
Create the Lagrangian finite element.
Create a DoFHandler, which is associated with the triangulation and distributed with the finite element.
Create the mapping object, which is required in generating the map from DoF indices to support points.
Generate a list of all DoF indices.
Get the spatial coordinates of the support points associated with DoF indices.
Calculate the average mesh cell size at each support point.
Initialize the cluster tree \(T(I)\) and \(T(J)\) for all the DoF indices.
Partition the cluster tree.
Print the cluster tree.
Create the block cluster tree.
Perform admissible partition on the block cluster tree.
Print the block cluster tree, even though there is only a root node.
Create a deal.ii vector storing the block cluster levels for all DoFs.
     Iterate through the \form#0 component of each block cluster and get
the level of each DoF in \(\tau\). Then assign the level value to all DoFs contained in the cluster \(\tau\).
Cluster indices in a cluster tree: on level 2.
Save the block cluster data matrices.
References ClusterTree< spacedim, Number >::get_leaf_set(), map_dofs_to_average_cell_size(), ClusterTree< spacedim, Number >::partition(), and BlockClusterTree< spacedim, Number >::partition().