laplace-bem: LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType > Class Template Reference
LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType > Class Template Reference
#include <laplace_bem.h>
Public Member Functions
KernelPulledbackToUnitCell (const LaplaceKernel::KernelFunction< spacedim, RangeNumberType > &kernel_function, const CellNeighboringType &cell_neighboring_type, const std::vector< Point< spacedim >> &kx_support_points, const std::vector< Point< spacedim >> &ky_support_points, const FiniteElement< dim, spacedim > &kx_fe, const FiniteElement< dim, spacedim > &ky_fe, const unsigned int kx_dof_index=0, const unsigned int ky_dof_index=0)
KernelPulledbackToUnitCell (const LaplaceKernel::KernelFunction< spacedim, RangeNumberType > &kernel_function, const CellNeighboringType &cell_neighboring_type, const std::vector< Point< spacedim >> &kx_support_points, const std::vector< Point< spacedim >> &ky_support_points, const FiniteElement< dim, spacedim > &kx_fe, const FiniteElement< dim, spacedim > &ky_fe, const BEMValues< dim, spacedim, RangeNumberType > *bem_values, const unsigned int kx_dof_index=0, const unsigned int ky_dof_index=0)
KernelPulledbackToUnitCell (const LaplaceKernel::KernelFunction< spacedim, RangeNumberType > &kernel_function, const CellNeighboringType &cell_neighboring_type, const std::vector< Point< spacedim >> &kx_support_points, const std::vector< Point< spacedim >> &ky_support_points, const FiniteElement< dim, spacedim > &kx_fe, const FiniteElement< dim, spacedim > &ky_fe, const BEMValues< dim, spacedim, RangeNumberType > *bem_values, const PairCellWiseScratchData *scratch, const unsigned int kx_dof_index=0, const unsigned int ky_dof_index=0)
virtual ~KernelPulledbackToUnitCell ()
KernelPulledbackToUnitCell & operator= (const KernelPulledbackToUnitCell &f)
void reinit (const CellNeighboringType &cell_neighboring_type, const std::vector< Point< spacedim >> &kx_support_points, const std::vector< Point< spacedim >> &ky_support_points, const FiniteElement< dim, spacedim > &kx_fe, const FiniteElement< dim, spacedim > &ky_fe)
void set_kx_dof_index (const unsigned int kx_dof_index)
void set_ky_dof_index (const unsigned int ky_dof_index)
virtual RangeNumberType value (const Point< dim > &x_hat, const Point< dim > &y_hat, const unsigned int component=0) const
virtual RangeNumberType value (const unsigned int k3_index, const unsigned int quad_no, const unsigned int component=0) const
virtual void vector_value (const Point< dim > &x_hat, const Point< dim > &y_hat, Vector< RangeNumberType > &values) const
virtual void value_list (const std::vector< Point< dim >> &x_hat_list, const std::vector< Point< dim >> &y_hat_list, std::vector< RangeNumberType > &values, const unsigned int component=0) const
virtual void vector_value_list (const std::vector< Point< dim >> &x_hat_list, const std::vector< Point< dim >> &y_hat_list, std::vector< Vector< RangeNumberType >> &values) const
Public Attributes
const unsigned int n_components
Static Public Attributes
static const unsigned int dimension = dim
Private Attributes
const LaplaceKernel::KernelFunction< spacedim, RangeNumberType > & kernel_function
CellNeighboringType cell_neighboring_type
const std::vector< Point< spacedim > > & kx_support_points
const std::vector< Point< spacedim > > & ky_support_points
const FiniteElement< dim, spacedim > & kx_fe
const FiniteElement< dim, spacedim > & ky_fe
const BEMValues< dim, spacedim, RangeNumberType > * bem_values
const PairCellWiseScratchData * scratch
unsigned int kx_dof_index
unsigned int ky_dof_index
Detailed Description
template<int dim, int spacedim, typename RangeNumberType = double>
class LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >
Kernel function pulled back to the unit cell.
Note
The unit cell has the manifold dimension dim.
Constructor & Destructor Documentation
KernelPulledbackToUnitCell() [1/3]
template<int dim, int spacedim, typename RangeNumberType > LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::KernelPulledbackToUnitCell (const LaplaceKernel::KernelFunction< spacedim, RangeNumberType > & kernel_function, const CellNeighboringType & cell_neighboring_type, const std::vector< Point< spacedim >> & kx_support_points, const std::vector< Point< spacedim >> & ky_support_points, const FiniteElement< dim, spacedim > & kx_fe, const FiniteElement< dim, spacedim > & ky_fe, const unsigned int kx_dof_index = 0, const unsigned int ky_dof_index = 0)
Constructor without BEMValues precalculation.
Parameters
kernel_function Kernel function defined in the original space, which has dimension spacedim.
cell_neighboring_type
kx_support_points Permuted list of support points in \(K_x\) in the lexicographic order.
ky_support_points Permuted list of support points in \(K_y\) in the lexicographic order or reversed lexicographic order, which depends on the cell neighboring type.
kx_fe
ky_fe
kx_dof_index Index for accessing the list of DoFs in the lexicographic order in \(K_x\).
ky_dof_index Index for accessing the list of DoFs in the lexicographic order in \(K_y\).
Referenced by LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::KernelPulledbackToUnitCell().
KernelPulledbackToUnitCell() [2/3]
template<int dim, int spacedim, typename RangeNumberType > LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::KernelPulledbackToUnitCell (const LaplaceKernel::KernelFunction< spacedim, RangeNumberType > & kernel_function, const CellNeighboringType & cell_neighboring_type, const std::vector< Point< spacedim >> & kx_support_points, const std::vector< Point< spacedim >> & ky_support_points, const FiniteElement< dim, spacedim > & kx_fe, const FiniteElement< dim, spacedim > & ky_fe, const BEMValues< dim, spacedim, RangeNumberType > * bem_values, const unsigned int kx_dof_index = 0, const unsigned int ky_dof_index = 0)
Constructor with BEMValues precalculation.
Parameters
kernel_function Kernel function defined in the original space, which has dimension spacedim.
cell_neighboring_type
kx_support_points Permuted list of support points in \(K_x\) in the lexicographic order.
ky_support_points Permuted list of support points in \(K_y\) in the lexicographic order or reversed lexicographic order, which depends on the cell neighboring type.
kx_fe
ky_fe
bem_values Pointer to the precalculated BEMValues, which contains shape function values and their gradient values on the quadrature points.
kx_dof_index Index for accessing the list of DoFs in the lexicographic order in \(K_x\).
ky_dof_index Index for accessing the list of DoFs in the lexicographic order in \(K_y\).
References LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::KernelPulledbackToUnitCell().
KernelPulledbackToUnitCell() [3/3]
template<int dim, int spacedim, typename RangeNumberType > LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::KernelPulledbackToUnitCell (const LaplaceKernel::KernelFunction< spacedim, RangeNumberType > & kernel_function, const CellNeighboringType & cell_neighboring_type, const std::vector< Point< spacedim >> & kx_support_points, const std::vector< Point< spacedim >> & ky_support_points, const FiniteElement< dim, spacedim > & kx_fe, const FiniteElement< dim, spacedim > & ky_fe, const BEMValues< dim, spacedim, RangeNumberType > * bem_values, const PairCellWiseScratchData * scratch, const unsigned int kx_dof_index = 0, const unsigned int ky_dof_index = 0)
Constructor with BEMValues precalculation, which is also oriented for parallelization, i.e., it accepts the scratch data as one of its arguments.
Parameters
kernel_function Kernel function defined in the original space, which has dimension spacedim.
cell_neighboring_type
kx_support_points Permuted list of support points in \(K_x\) in the lexicographic order.
ky_support_points Permuted list of support points in \(K_y\) in the lexicographic order or reversed lexicographic order, which depends on the cell neighboring type.
kx_fe
ky_fe
bem_values Pointer to the precalculated BEMValues, which contains shape function values and their gradient values on the quadrature points.
scratch
kx_dof_index Index for accessing the list of DoFs in the lexicographic order in \(K_x\).
ky_dof_index Index for accessing the list of DoFs in the lexicographic order in \(K_y\).
References LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::kx_support_points, LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::ky_support_points, and LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::~KernelPulledbackToUnitCell().
~KernelPulledbackToUnitCell()
template<int dim, int spacedim, typename RangeNumberType > LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::~KernelPulledbackToUnitCell () virtual default
Destructor.
Note
Since this class has only references to other objects as its members and their memory is not managed by this class, the destructor provided by the compiler is adopted.
Referenced by LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::KernelPulledbackToUnitCell().
Member Function Documentation
reinit()
template<int dim, int spacedim, typename RangeNumberType > void LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::reinit (const CellNeighboringType & cell_neighboring_type, const std::vector< Point< spacedim >> & kx_support_points, const std::vector< Point< spacedim >> & ky_support_points, const FiniteElement< dim, spacedim > & kx_fe, const FiniteElement< dim, spacedim > & ky_fe)
Associate the KernelPulledbackToUnitCell with support points and finite element data for a new pair of cells.
Parameters
cell_neighboring_type
kx_support_points Permuted list of support points in \(K_x\) in the lexicographic order.
ky_support_points Permuted list of support points in \(K_y\) in the lexicographic order or reversed lexicographic order, which depends on the cell neighboring type.
kx_fe
ky_fe
References LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::kx_dof_index, LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::kx_support_points, LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::ky_dof_index, and LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::ky_support_points.
value()
template<int dim, int spacedim, typename RangeNumberType > RangeNumberType LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::value (const Point< dim > & x_hat, const Point< dim > & y_hat, const unsigned int component = 0) const virtual
Evaluation of the kernel function at the specified coordinates in the unit cell.
Note
This version of value does not rely on the precalculated BEMValues, hence it will calculate Jacobian and normal vector on the fly.
References LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::kx_support_points, LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::ky_support_points, and LaplaceBEM::transform_unit_to_permuted_real_cell().
Member Data Documentation
dimension
template<int dim, int spacedim, typename RangeNumberType = double> const unsigned int LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::dimension = dim static
Manifold dimension
kx_dof_index
template<int dim, int spacedim, typename RangeNumberType = double> unsigned int LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::kx_dof_index private
The current index for accessing the list of DoFs in the lexicographic order in \(K_x\).
Referenced by LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::reinit().
kx_support_points
template<int dim, int spacedim, typename RangeNumberType = double> const std::vector<Point<spacedim> >& LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::kx_support_points private
Permuted list of support points in \(K_x\) in the lexicographic order.
Referenced by LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::KernelPulledbackToUnitCell(), LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::reinit(), and LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::value().
ky_dof_index
template<int dim, int spacedim, typename RangeNumberType = double> unsigned int LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::ky_dof_index private
The current index for accessing the list of DoFs in the lexicographic order or reversed lexicographic order in \(K_y\).
Referenced by LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::reinit().
ky_support_points
template<int dim, int spacedim, typename RangeNumberType = double> const std::vector<Point<spacedim> >& LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::ky_support_points private
Permuted list of support points in \(K_y\) in the lexicographic order or reversed lexicographic order, which depends on the cell neighboring type.
Referenced by LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::KernelPulledbackToUnitCell(), LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::reinit(), and LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::value().
The documentation for this class was generated from the following file:
/home/jihuan/Projects/deal.ii/program/dealii-9.1.1/examples/laplace-bem/include/laplace_bem.h