laplace-bem: SimpleBoundingBox< spacedim, Number > Class Template Reference
SimpleBoundingBox< spacedim, Number > Class Template Reference
#include <simple_bounding_box.h>
Public Member Functions
SimpleBoundingBox ()
SimpleBoundingBox (const Point< spacedim, Number > &corner1, const Point< spacedim, Number > &corner2)
SimpleBoundingBox (const std::pair< Point< spacedim, Number >, Point< spacedim, Number >> &point_pair)
SimpleBoundingBox (const std::vector< Point< spacedim, Number >> &points)
template<int dim>
SimpleBoundingBox (const Mapping< dim, spacedim > &mapping, const DoFHandler< dim, spacedim > &dof_handler)
SimpleBoundingBox (const std::vector< types::global_dof_index > &dof_indices, const std::vector< Point< spacedim, Number >> &all_support_points)
SimpleBoundingBox (const SimpleBoundingBox< spacedim, Number > &bbox)
Number volume () const
std::pair< Point< spacedim, Number >, Point< spacedim, Number > > & get_boundary_points ()
const std::pair< Point< spacedim, Number >, Point< spacedim, Number > > & get_boundary_points () const
bool point_inside (const Point< spacedim, Number > &p) const
unsigned int coordinate_index_with_longest_dimension () const
std::pair< SimpleBoundingBox< spacedim, Number >, SimpleBoundingBox< spacedim, Number > > divide_geometrically () const
Private Member Functions
void calculate_bounding_box (const std::vector< Point< spacedim, Number >> &points)
void calculate_bounding_box (const std::vector< types::global_dof_index > &dof_indices, const std::vector< Point< spacedim, Number >> &all_support_points)
Private Attributes
std::pair< Point< spacedim, Number >, Point< spacedim, Number > > boundary_points
Friends
template<int spacedim1, typename Number1 >
std::ostream & operator<< (std::ostream &out, const SimpleBoundingBox< spacedim1, Number1 > &bbox)
Detailed Description
template<int spacedim, typename Number = double>
class SimpleBoundingBox< spacedim, Number >
Class implementing a simple axis-parallel bounding box. N.B. This class only has the spacedim template argument but without the dim template argument, which means an axis-parallel bounding box always has the same dimension as the specified space dimension. Therefore, the bounding box for a 2D surface in 3D space is still a 3D box.
Constructor & Destructor Documentation
SimpleBoundingBox() [1/7]
template<int spacedim, typename Number > SimpleBoundingBox< spacedim, Number >::SimpleBoundingBox ()
Default constructor with two boundary points being both zeros.
SimpleBoundingBox() [2/7]
template<int spacedim, typename Number > SimpleBoundingBox< spacedim, Number >::SimpleBoundingBox (const Point< spacedim, Number > & corner1, const Point< spacedim, Number > & corner2)
Constructor from two corner points.
SimpleBoundingBox() [3/7]
template<int spacedim, typename Number > SimpleBoundingBox< spacedim, Number >::SimpleBoundingBox (const std::pair< Point< spacedim, Number >, Point< spacedim, Number >> & point_pair)
Constructor from a pair of corner points.
Parameters
point_pair
SimpleBoundingBox() [4/7]
template<int spacedim, typename Number > SimpleBoundingBox< spacedim, Number >::SimpleBoundingBox (const std::vector< Point< spacedim, Number >> & points)
Constructor from a vector of points.
References SimpleBoundingBox< spacedim, Number >::calculate_bounding_box().
SimpleBoundingBox() [5/7]
template<int spacedim, typename Number > template<int dim> SimpleBoundingBox< spacedim, Number >::SimpleBoundingBox (const Mapping< dim, spacedim > & mapping, const DoFHandler< dim, spacedim > & dof_handler)
Constructor from a Mapping and a DoFHandler. N.B. This is a template constructor with the argument dim as manifold dimension. The resulted bounding box contains the support points associated with all DoFs within the DoFHandler.
References SimpleBoundingBox< spacedim, Number >::calculate_bounding_box().
SimpleBoundingBox() [6/7]
template<int spacedim, typename Number > SimpleBoundingBox< spacedim, Number >::SimpleBoundingBox (const std::vector< types::global_dof_index > & dof_indices, const std::vector< Point< spacedim, Number >> & all_support_points)
Constructor from a specified DoF index set. The support point coordinates for all DoFs have been placed into all_support_points.
Parameters
dof_indices The DoF index set, for which the bounding box is to be generated.
all_support_points The const reference to the list of all support points associated with a DoFHandler.
References SimpleBoundingBox< spacedim, Number >::calculate_bounding_box().
SimpleBoundingBox() [7/7]
template<int spacedim, typename Number > SimpleBoundingBox< spacedim, Number >::SimpleBoundingBox (const SimpleBoundingBox< spacedim, Number > & bbox)
Copy constructor
Member Function Documentation
calculate_bounding_box() [1/2]
template<int spacedim, typename Number > void SimpleBoundingBox< spacedim, Number >::calculate_bounding_box (const std::vector< Point< spacedim, Number >> & points) private
Calculate the bounding box from a list of points.
Initialize the two boundary points to be the first point in the list.
Calculate the minimum and the maximum coordinate for each dimension.
References SimpleBoundingBox< spacedim, Number >::boundary_points.
Referenced by SimpleBoundingBox< spacedim, Number >::SimpleBoundingBox().
calculate_bounding_box() [2/2]
template<int spacedim, typename Number > void SimpleBoundingBox< spacedim, Number >::calculate_bounding_box (const std::vector< types::global_dof_index > & dof_indices, const std::vector< Point< spacedim, Number >> & all_support_points) private
Calculate the bounding box from a list of DoF indices.
Parameters
dof_indices The DoF index set.
all_support_points The const reference to the list of all support points associated with a DoFHandler.
Initialize the two boundary points to be the point associated with the first DoF index.
Calculate the minimum and the maximum coordinate for each dimension.
References SimpleBoundingBox< spacedim, Number >::boundary_points.
coordinate_index_with_longest_dimension()
template<int spacedim, typename Number > unsigned int SimpleBoundingBox< spacedim, Number >::coordinate_index_with_longest_dimension () const
Get the index to the coordinate component, which has the longest dimension.
Returns
Index to the coordinate component, which should be in the range \([0, {\rm spacedim})\).
References SimpleBoundingBox< spacedim, Number >::boundary_points.
Referenced by SimpleBoundingBox< spacedim, Number >::divide_geometrically().
divide_geometrically()
template<int spacedim, typename Number > std::pair< SimpleBoundingBox< spacedim, Number >, SimpleBoundingBox< spacedim, Number > > SimpleBoundingBox< spacedim, Number >::divide_geometrically () const
Bisect the bounding box along the longest coordinate direction.
Returns
Calculate the coordinate index which has the longest dimension.
Modify the coordinate_index 'th coordinate of the top corner point in the first box.
Modify the coordinate_index 'th coordinate of the bottom corner point in the second box.
References SimpleBoundingBox< spacedim, Number >::coordinate_index_with_longest_dimension(), and SimpleBoundingBox< spacedim, Number >::get_boundary_points().
get_boundary_points() [1/2]
template<int spacedim, typename Number > std::pair< Point< spacedim, Number >, Point< spacedim, Number > > & SimpleBoundingBox< spacedim, Number >::get_boundary_points ()
Get the two corner points of the bounding box (mutable version).
Returns
The reference to the pair of corner points. The point with a smaller coordinate in each dimension is the first.
References SimpleBoundingBox< spacedim, Number >::boundary_points.
Referenced by SimpleBoundingBox< spacedim, Number >::divide_geometrically().
get_boundary_points() [2/2]
template<int spacedim, typename Number > const std::pair< Point< spacedim, Number >, Point< spacedim, Number > > & SimpleBoundingBox< spacedim, Number >::get_boundary_points () const
Get the two corner points of the bounding box (const version).
Returns
The const reference to the pair of corner points. The point with a smaller coordinate in each dimension is the first.
References SimpleBoundingBox< spacedim, Number >::boundary_points.
point_inside()
template<int spacedim, typename Number > bool SimpleBoundingBox< spacedim, Number >::point_inside (const Point< spacedim, Number > & p) const
Determine if a given point lies within the bounding box.
Make a predicate on if the point lies outside the bounding box.
References SimpleBoundingBox< spacedim, Number >::boundary_points.
volume()
template<int spacedim, typename Number > Number SimpleBoundingBox< spacedim, Number >::volume () const
Calculate the volume of the bounding box.
Returns
Volume of the bounding box.
References SimpleBoundingBox< spacedim, Number >::boundary_points.
Member Data Documentation
boundary_points
template<int spacedim, typename Number = double> std::pair<Point<spacedim, Number>, Point<spacedim, Number> > SimpleBoundingBox< spacedim, Number >::boundary_points private
Two corner points of the bounding box. The point in the pair is the bottom corner, i.e. it has a smaller component coordinate in each dimension; while the second point is the top corner.
Referenced by SimpleBoundingBox< spacedim, Number >::calculate_bounding_box(), SimpleBoundingBox< spacedim, Number >::coordinate_index_with_longest_dimension(), SimpleBoundingBox< spacedim, Number >::get_boundary_points(), SimpleBoundingBox< spacedim, Number >::point_inside(), and SimpleBoundingBox< spacedim, Number >::volume().
The documentation for this class was generated from the following file:
/home/jihuan/Projects/deal.ii/program/dealii-9.1.1/examples/laplace-bem/include/simple_bounding_box.h