laplace-bem: RkMatrix< Number > Class Template Reference
RkMatrix< Number > Class Template Reference
Public Types
using size_type = std::make_unsigned< types::blas_int >::type
Public Member Functions
RkMatrix ()
RkMatrix (const size_type m, const size_type n, const size_type fixed_rank_k)
RkMatrix (const size_type fixed_rank_k, LAPACKFullMatrixExt< Number > &M)
RkMatrix (const size_type fixed_rank_k, LAPACKFullMatrixExt< Number > &M, LAPACKFullMatrixExt< Number > &C, LAPACKFullMatrixExt< Number > &D)
RkMatrix (LAPACKFullMatrixExt< Number > &M)
RkMatrix (const std::vector< types::global_dof_index > &tau, const std::vector< types::global_dof_index > &sigma, const size_type fixed_rank_k, const LAPACKFullMatrixExt< Number > &M)
RkMatrix (const std::vector< types::global_dof_index > &tau, const std::vector< types::global_dof_index > &sigma, const LAPACKFullMatrixExt< Number > &M)
RkMatrix (const std::vector< types::global_dof_index > &tau, const std::vector< types::global_dof_index > &sigma, const size_type fixed_rank_k, const LAPACKFullMatrixExt< Number > &M, const std::map< types::global_dof_index, size_t > &row_index_global_to_local_map_for_M, const std::map< types::global_dof_index, size_t > &col_index_global_to_local_map_for_M)
RkMatrix (const std::vector< types::global_dof_index > &tau, const std::vector< types::global_dof_index > &sigma, const LAPACKFullMatrixExt< Number > &M, const std::map< types::global_dof_index, size_t > &row_index_global_to_local_map_for_M, const std::map< types::global_dof_index, size_t > &col_index_global_to_local_map_for_M)
RkMatrix (const std::vector< types::global_dof_index > &tau, const std::vector< types::global_dof_index > &sigma, const size_type fixed_rank_k, const RkMatrix< Number > &M)
RkMatrix (const std::vector< types::global_dof_index > &tau, const std::vector< types::global_dof_index > &sigma, const RkMatrix< Number > &M)
RkMatrix (const std::vector< types::global_dof_index > &tau, const std::vector< types::global_dof_index > &sigma, const size_type fixed_rank_k, const RkMatrix< Number > &M, const std::map< types::global_dof_index, size_t > &row_index_global_to_local_map_for_M, const std::map< types::global_dof_index, size_t > &col_index_global_to_local_map_for_M)
RkMatrix (const std::vector< types::global_dof_index > &tau, const std::vector< types::global_dof_index > &sigma, const RkMatrix< Number > &M, const std::map< types::global_dof_index, size_t > &row_index_global_to_local_map_for_M, const std::map< types::global_dof_index, size_t > &col_index_global_to_local_map_for_M)
RkMatrix (const LAPACKFullMatrixExt< Number > &A, const LAPACKFullMatrixExt< Number > &B)
RkMatrix (const size_type fixed_rank_k, const RkMatrix< Number > &M1, const RkMatrix< Number > &M2, bool is_horizontal_split)
RkMatrix (const size_type fixed_rank_k, const std::map< types::global_dof_index, size_t > &row_index_global_to_local_map_for_M, const std::map< types::global_dof_index, size_t > &col_index_global_to_local_map_for_M, const RkMatrix< Number > &M1, const std::vector< types::global_dof_index > &M1_tau_index_set, const std::vector< types::global_dof_index > &M1_sigma_index_set, const RkMatrix< Number > &M2, const std::vector< types::global_dof_index > &M2_tau_index_set, const std::vector< types::global_dof_index > &M2_sigma_index_set, bool is_horizontal_split)
RkMatrix (const size_type fixed_rank_k, const RkMatrix< Number > &M11, const RkMatrix< Number > &M12, const RkMatrix< Number > &M21, const RkMatrix< Number > &M22, const Number rank_factor=1.0)
RkMatrix (const size_type fixed_rank_k, const std::map< types::global_dof_index, size_t > &row_index_global_to_local_map_for_M, const std::map< types::global_dof_index, size_t > &col_index_global_to_local_map_for_M, const RkMatrix< Number > &M11, const std::vector< types::global_dof_index > &M11_tau_index_set, const std::vector< types::global_dof_index > &M11_sigma_index_set, const RkMatrix< Number > &M12, const std::vector< types::global_dof_index > &M12_tau_index_set, const std::vector< types::global_dof_index > &M12_sigma_index_set, const RkMatrix< Number > &M21, const std::vector< types::global_dof_index > &M21_tau_index_set, const std::vector< types::global_dof_index > &M21_sigma_index_set, const RkMatrix< Number > &M22, const std::vector< types::global_dof_index > &M22_tau_index_set, const std::vector< types::global_dof_index > &M22_sigma_index_set, const Number rank_factor=1.0)
RkMatrix (const RkMatrix< Number > &matrix)
RkMatrix< Number > & operator= (const RkMatrix< Number > &matrix)
void reinit (const size_type m, const size_type n, const size_type fixed_rank_k)
size_type get_m () const
size_type get_n () const
size_type get_rank () const
size_type get_formal_rank () const
LAPACKFullMatrixExt< Number > & get_A ()
const LAPACKFullMatrixExt< Number > & get_A () const
LAPACKFullMatrixExt< Number > & get_B ()
const LAPACKFullMatrixExt< Number > & get_B () const
void convertToFullMatrix (LAPACKFullMatrixExt< Number > &matrix) const
void restrictToFullMatrix (const std::vector< types::global_dof_index > &tau, const std::vector< types::global_dof_index > &sigma, LAPACKFullMatrixExt< Number > &matrix) const
void restrictToFullMatrix (const std::vector< types::global_dof_index > &tau, const std::vector< types::global_dof_index > &sigma, const std::map< types::global_dof_index, size_t > &row_index_global_to_local_map_for_rk, const std::map< types::global_dof_index, size_t > &col_index_global_to_local_map_for_rk, LAPACKFullMatrixExt< Number > &matrix) const
void print_formatted (std::ostream &out, const unsigned int precision=3, const bool scientific=true, const unsigned int width=0, const char *zero_string="0", const double denominator=1., const double threshold=0.) const
void print_formatted_to_mat (std::ostream &out, const std::string &name, const unsigned int precision=8, const bool scientific=true, const unsigned int width=0, const char *zero_string="0", const double denominator=1., const double threshold=0.) const
void truncate_to_rank (size_type new_rank)
void truncate_to_rank (size_type new_rank, LAPACKFullMatrixExt< Number > &C, LAPACKFullMatrixExt< Number > &D)
void calc_rank_upper_bound ()
void vmult (Vector< Number > &y, const Vector< Number > &x, const bool adding=false) const
void Tvmult (Vector< Number > &y, const Vector< Number > &x, const bool adding=false) const
void add (RkMatrix< Number > &M, const RkMatrix< Number > &M2) const
void add (RkMatrix< Number > &M, const Number m2, const RkMatrix< Number > &M2) const
void add (const RkMatrix< Number > &M1)
void add (const Number m1, const RkMatrix< Number > &M1)
void add (RkMatrix< Number > &M, const RkMatrix< Number > &M2, const size_type fixed_rank_k) const
void add (RkMatrix< Number > &M, const RkMatrix< Number > &M2, const size_type fixed_rank_k, LAPACKFullMatrixExt< Number > &C, LAPACKFullMatrixExt< Number > &D) const
void add (RkMatrix< Number > &M, const Number m2, const RkMatrix< Number > &M2, const size_type fixed_rank_k) const
void add (RkMatrix< Number > &M, const Number m2, const RkMatrix< Number > &M2, const size_type fixed_rank_k, LAPACKFullMatrixExt< Number > &C, LAPACKFullMatrixExt< Number > &D) const
void add (const RkMatrix< Number > &M1, const size_type fixed_rank_k)
void add (const RkMatrix< Number > &M1, const size_type fixed_rank_k, LAPACKFullMatrixExt< Number > &C, LAPACKFullMatrixExt< Number > &D)
void add (const Number m1, const RkMatrix< Number > &M1, const size_type fixed_rank_k)
void add (const Number m1, const RkMatrix< Number > &M1, const size_type fixed_rank_k, LAPACKFullMatrixExt< Number > &C, LAPACKFullMatrixExt< Number > &D)
void assemble_from_rkmatrix (const std::map< types::global_dof_index, size_t > &row_index_global_to_local_map, const std::map< types::global_dof_index, size_t > &col_index_global_to_local_map, const RkMatrix< Number > &M, const std::vector< types::global_dof_index > &M_tau_index_set, const std::vector< types::global_dof_index > &M_sigma_index_set, const size_type fixed_rank_k)
void assemble_from_rkmatrix (const std::map< types::global_dof_index, size_t > &row_index_global_to_local_map, const std::map< types::global_dof_index, size_t > &col_index_global_to_local_map, const RkMatrix< Number > &M, const std::vector< types::global_dof_index > &M_tau_index_set, const std::vector< types::global_dof_index > &M_sigma_index_set, const size_type fixed_rank_k, LAPACKFullMatrixExt< Number > &C, LAPACKFullMatrixExt< Number > &D)
Private Attributes
LAPACKFullMatrixExt< Number > A
LAPACKFullMatrixExt< Number > B
size_type rank
size_type formal_rank
size_type m
size_type n
Friends
template<int spacedim1, typename Number1 >
void h_rk_mmult (HMatrix< spacedim1, Number1 > &M1, const RkMatrix< Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void h_rk_mmult (const Number1 alpha, HMatrix< spacedim1, Number1 > &M1, const RkMatrix< Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void h_rk_mTmult (HMatrix< spacedim1, Number1 > &M1, const RkMatrix< Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void h_rk_mTmult (const Number1 alpha, HMatrix< spacedim1, Number1 > &M1, const RkMatrix< Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void h_rk_mmult_for_h_h_mmult (HMatrix< spacedim1, Number1 > *M1, const HMatrix< spacedim1, Number1 > *M2, HMatrix< spacedim1, Number1 > *M, bool is_M1M2_last_in_M_Sigma_P)
template<int spacedim1, typename Number1 >
void rk_h_mmult (const RkMatrix< Number1 > &M1, HMatrix< spacedim1, Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void rk_h_mmult (const Number1 alpha, const RkMatrix< Number1 > &M1, HMatrix< spacedim1, Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void rk_h_mTmult (const RkMatrix< Number1 > &M1, HMatrix< spacedim1, Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void rk_h_mTmult (const Number1 alpha, const RkMatrix< Number1 > &M1, HMatrix< spacedim1, Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void rk_h_mmult_for_h_h_mmult (const HMatrix< spacedim1, Number1 > *M1, HMatrix< spacedim1, Number1 > *M2, HMatrix< spacedim1, Number1 > *M, bool is_M1M2_last_in_M_Sigma_P)
template<int spacedim1, typename Number1 >
void h_f_mmult (HMatrix< spacedim1, Number1 > &M1, const LAPACKFullMatrixExt< Number1 > &M2, LAPACKFullMatrixExt< Number1 > &M)
template<int spacedim1, typename Number1 >
void h_f_mmult (const Number1 alpha, HMatrix< spacedim1, Number1 > &M1, const LAPACKFullMatrixExt< Number1 > &M2, LAPACKFullMatrixExt< Number1 > &M)
template<int spacedim1, typename Number1 >
void h_f_mTmult (HMatrix< spacedim1, Number1 > &M1, const LAPACKFullMatrixExt< Number1 > &M2, LAPACKFullMatrixExt< Number1 > &M)
template<int spacedim1, typename Number1 >
void h_f_mTmult (const Number1 alpha, HMatrix< spacedim1, Number1 > &M1, const LAPACKFullMatrixExt< Number1 > &M2, LAPACKFullMatrixExt< Number1 > &M)
template<int spacedim1, typename Number1 >
void h_f_mmult (HMatrix< spacedim1, Number1 > &M1, const LAPACKFullMatrixExt< Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void h_f_mmult (const Number1 alpha, HMatrix< spacedim1, Number1 > &M1, const LAPACKFullMatrixExt< Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void h_f_mTmult (HMatrix< spacedim1, Number1 > &M1, const LAPACKFullMatrixExt< Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void h_f_mTmult (const Number1 alpha, HMatrix< spacedim1, Number1 > &M1, const LAPACKFullMatrixExt< Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void h_f_mmult_for_h_h_mmult (HMatrix< spacedim1, Number1 > *M1, const HMatrix< spacedim1, Number1 > *M2, HMatrix< spacedim1, Number1 > *M, bool is_M1M2_last_in_M_Sigma_P)
template<int spacedim1, typename Number1 >
void f_h_mmult (const LAPACKFullMatrixExt< Number1 > &M1, HMatrix< spacedim1, Number1 > &M2, LAPACKFullMatrixExt< Number1 > &M)
template<int spacedim1, typename Number1 >
void f_h_mmult (const Number1 alpha, const LAPACKFullMatrixExt< Number1 > &M1, HMatrix< spacedim1, Number1 > &M2, LAPACKFullMatrixExt< Number1 > &M)
template<int spacedim1, typename Number1 >
void f_h_mTmult (const LAPACKFullMatrixExt< Number1 > &M1, HMatrix< spacedim1, Number1 > &M2, LAPACKFullMatrixExt< Number1 > &M)
template<int spacedim1, typename Number1 >
void f_h_mTmult (const Number1 alpha, const LAPACKFullMatrixExt< Number1 > &M1, HMatrix< spacedim1, Number1 > &M2, LAPACKFullMatrixExt< Number1 > &M)
template<int spacedim1, typename Number1 >
void f_h_mmult (const LAPACKFullMatrixExt< Number1 > &M1, HMatrix< spacedim1, Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void f_h_mmult (const Number1 alpha, const LAPACKFullMatrixExt< Number1 > &M1, HMatrix< spacedim1, Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void f_h_mTmult (const LAPACKFullMatrixExt< Number1 > &M1, HMatrix< spacedim1, Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void f_h_mTmult (const Number1 alpha, const LAPACKFullMatrixExt< Number1 > &M1, HMatrix< spacedim1, Number1 > &M2, RkMatrix< Number1 > &M)
template<int spacedim1, typename Number1 >
void f_h_mmult_for_h_h_mmult (const HMatrix< spacedim1, Number1 > *M1, HMatrix< spacedim1, Number1 > *M2, HMatrix< spacedim1, Number1 > *M, bool is_M1M2_last_in_M_Sigma_P)
template<typename Number1 >
void print_rkmatrix_to_mat (std::ostream &out, const std::string &name, const RkMatrix< Number1 > &values, const unsigned int precision, const bool scientific, const unsigned int width, const char *zero_string, const double denominator, const double threshold)
Member Typedef Documentation
size_type
template<typename Number = double> using RkMatrix< Number >::size_type = std::make_unsigned<types::blas_int>::type
Declare the type for container size.
Constructor & Destructor Documentation
RkMatrix() [1/19]
template<typename Number > RkMatrix< Number >::RkMatrix ()
Default constructor.
RkMatrix() [2/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const size_type m, const size_type n, const size_type fixed_rank_k)
Construct a zero-valued rank-k matrix with the specified matrix dimension and rank.
Parameters
m
n
fixed_rank_k
If the given fixed_rank_k is larger than the minimum matrix dimension \(\min\{m, n\}\), simply set it as this value.
Only when the effective rank is larger than zero and the matrix has non-zero row or column dimension, memory for the component matrices is allocated.
Even though the component matrices are zero-valued at the moment, because the current rank-k matrix is to be assigned with effect data, its rank should be still set to the effective_rank.
References RkMatrix< Number >::formal_rank, and RkMatrix< Number >::rank.
RkMatrix() [3/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const size_type fixed_rank_k, LAPACKFullMatrixExt< Number > & M)
Construct a rank-k matrix by conversion from a full matrix M with rank truncation.
Note
This method converts a full matrix to a rank-k matrix, which implements the operator \(\mathcal{T}_{r}^{\mathcal{R} \leftarrow \mathcal{F}}\) in (7.2) in Hackbusch's \(\mathcal{H}\)-matrix book. The original full matrix will be modified since SVD will be applied to it.
Parameters
fixed_rank_k
M
If the size of the row or column dimension of M is zero or the given rank is zero, do not allocate memory for the component matrices of the rank-k matrix, since there is no effective data.
Handle the case when the source full matrix is a scalar.
When the scalar value is zero. We do nothing here and the rank-k matrix still has a dimension \(1 \times 1\) with zero rank and empty component matrices.
When the scalar value is non-zero, both component matrices have the dimension \(1 \times 1\) and the rank-k matrix has rank 1.
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, and LAPACKFullMatrixExt< Number >::rank_k_decompose().
RkMatrix() [4/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const size_type fixed_rank_k, LAPACKFullMatrixExt< Number > & M, LAPACKFullMatrixExt< Number > & C, LAPACKFullMatrixExt< Number > & D)
Construct a rank-k matrix by conversion from a full matrix M with rank truncation. The error matrices are returned.
Note
This method converts a full matrix to a rank-k matrix, which implements the operator \(\mathcal{T}_{r}^{\mathcal{R} \leftarrow \mathcal{F}}\) in (7.2) in Hackbusch's \(\mathcal{H}\)-matrix book. The original full matrix will be modified since SVD will be applied to it.
Parameters
fixed_rank_k
M
C
D
If the size of the row or column dimension of M is zero or the given rank is zero, do not allocate memory for the component matrices of the rank-k matrix, since there is no effective data.
Set the error matrices as zero.
Handle the case when the source full matrix is a scalar.
When the scalar value is zero. We do nothing here and the rank-k matrix still has a dimension \(1 \times 1\) with zero rank and empty component matrices.
When the scalar value is non-zero, both component matrices have the dimension \(1 \times 1\) and the rank-k matrix has rank 1.
Set the error matrices as zero.
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, and LAPACKFullMatrixExt< Number >::rank_k_decompose().
RkMatrix() [5/19]
template<typename Number > RkMatrix< Number >::RkMatrix (LAPACKFullMatrixExt< Number > & M)
Construct a rank-k matrix by conversion from a full matrix M without rank truncation.
Note
The original full matrix will be modified since SVD will be applied to it.
Parameters
M
If the size of the row or column dimension of M is zero, do not allocate memory for the component matrices of the rank-k matrix, since there is no effective data.
Handle the case when the source full matrix is a scalar.
When the scalar value is zero. We do nothing here and the rank-k matrix still has a dimension \(1 \times 1\) with zero rank and empty component matrices.
When the scalar value is non-zero, both component matrices have the dimension \(1 \times 1\) and the rank-k matrix has rank 1.
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, and LAPACKFullMatrixExt< Number >::rank_k_decompose().
RkMatrix() [6/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const std::vector< types::global_dof_index > & tau, const std::vector< types::global_dof_index > & sigma, const size_type fixed_rank_k, const LAPACKFullMatrixExt< Number > & M)
Construct a rank-k matrix by restriction to the block cluster \(\tau \times \sigma\) with rank truncation from the full global matrix M defined on the complete block cluster \(I \times J\).
Note
This operation will not modify the full global matrix M.
Parameters
tau
sigma
fixed_rank_k
M
Convert the matrix block M_b in full matrix format to rank-k matrix format.
If the size of the row or column dimension of M is zero or the given rank is zero, do not allocate memory for the component matrices of the rank-k matrix, since there is no effective data.
Extract the data for the submatrix defined on the block cluster \(\tau \times \sigma\) from the full global matrix M.
Handle the case when the source full matrix is a scalar.
When the scalar value is zero. We do nothing here and the rank-k matrix still has a dimension \(1 \times 1\) with zero rank and empty component matrices.
When the scalar value is non-zero, both component matrices have the dimension \(1 \times 1\) and the rank-k matrix has rank 1.
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, and LAPACKFullMatrixExt< Number >::rank_k_decompose().
RkMatrix() [7/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const std::vector< types::global_dof_index > & tau, const std::vector< types::global_dof_index > & sigma, const LAPACKFullMatrixExt< Number > & M)
Construct a rank-k matrix by restriction to the block cluster \(\tau \times \sigma\) without rank truncation from the full global matrix M defined on the complete block cluster \(I \times J\).
Note
This operation will not modify the full global matrix M.
Parameters
tau
sigma
M
Convert the matrix block M_b in full matrix format to rank-k matrix format.
If the size of the row or column dimension of M is zero, do not allocate memory for the component matrices of the rank-k matrix, since there is no effective data.
Extract the data for the submatrix defined on the block cluster \(\tau \times \sigma\) from the full global matrix M.
Handle the case when the source full matrix is a scalar.
When the scalar value is zero. We do nothing here and the rank-k matrix still has a dimension \(1 \times 1\) with zero rank and empty component matrices.
When the scalar value is non-zero, both component matrices have the dimension \(1 \times 1\) and the rank-k matrix has rank 1.
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, and LAPACKFullMatrixExt< Number >::rank_k_decompose().
RkMatrix() [8/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const std::vector< types::global_dof_index > & tau, const std::vector< types::global_dof_index > & sigma, const size_type fixed_rank_k, const LAPACKFullMatrixExt< Number > & M, const std::map< types::global_dof_index, size_t > & row_index_global_to_local_map_for_M, const std::map< types::global_dof_index, size_t > & col_index_global_to_local_map_for_M)
Construct a rank-k matrix from by restriction to the block cluster \(\tau \times \sigma\) with rank truncation from the full local matrix M.
Note
The original full local matrix M will not be modified.
Parameters
tau
sigma
fixed_rank_k
M
row_index_global_to_local_map_for_M The map from the global row indices to the local indices of the matrix associated the H-matrix when first calling this recursive function.
col_index_global_to_local_map_for_M The map from the global column indices to the local indices of the matrix associated the H-matrix when first calling this recursive function.
Convert the matrix block M_b in full matrix format to rank-k format.
If the size of the row or column dimension of M is zero, do not allocate memory for the component matrices of the rank-k matrix, since there is no effective data.
Extract the data for the submatrix block \(b = \tau \times \sigma\) in the original matrix M.
Handle the case when the source full matrix is a scalar.
When the scalar value is zero. We do nothing here and the rank-k matrix still has a dimension \(1 \times 1\) with zero rank and empty component matrices.
When the scalar value is non-zero, both component matrices have the dimension \(1 \times 1\) and the rank-k matrix has rank 1.
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, and LAPACKFullMatrixExt< Number >::rank_k_decompose().
RkMatrix() [9/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const std::vector< types::global_dof_index > & tau, const std::vector< types::global_dof_index > & sigma, const LAPACKFullMatrixExt< Number > & M, const std::map< types::global_dof_index, size_t > & row_index_global_to_local_map_for_M, const std::map< types::global_dof_index, size_t > & col_index_global_to_local_map_for_M)
Construct a rank-k matrix from by restriction to the block cluster \(\tau \times \sigma\) without rank truncation from the full local matrix M.
Note
The original full local matrix M will not be modified.
Parameters
tau
sigma
M
row_index_global_to_local_map_for_M The map from the global row indices to the local indices of the matrix associated the H-matrix when first calling this recursive function.
col_index_global_to_local_map_for_M The map from the global column indices to the local indices of the matrix associated the H-matrix when first calling this recursive function.
Convert the matrix block M_b in full matrix format to rank-k format.
If the size of the row or column dimension of M is zero, do not allocate memory for the component matrices of the rank-k matrix, since there is no effective data.
Extract the data for the submatrix block \(b = \tau \times \sigma\) in the original matrix M.
Handle the case when the source full matrix is a scalar.
When the scalar value is zero. We do nothing here and the rank-k matrix still has a dimension \(1 \times 1\) with zero rank and empty component matrices.
When the scalar value is non-zero, both component matrices have the dimension \(1 \times 1\) and the rank-k matrix has rank 1.
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, and LAPACKFullMatrixExt< Number >::rank_k_decompose().
RkMatrix() [10/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const std::vector< types::global_dof_index > & tau, const std::vector< types::global_dof_index > & sigma, const size_type fixed_rank_k, const RkMatrix< Number > & M)
Construct a rank-k matrix by restriction to the block cluster \(\tau \times \sigma\) with rank truncation from the global rank-k matrix M.
Note
The original rank-k global matrix M will not be modified.
Parameters
tau
sigma
fixed_rank_k
M
Only when the formal rank of the current rank-k matrix is larger than zero, there will be actual initialization of component matrices and further restriction operation
Restrict the component matrix A of the original global rank-k matrix M to the cluster \(\tau\).
Restrict the component matrix B of the original global rank-k matrix M to the cluster \(\sigma\).
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, and RkMatrix< Number >::truncate_to_rank().
RkMatrix() [11/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const std::vector< types::global_dof_index > & tau, const std::vector< types::global_dof_index > & sigma, const RkMatrix< Number > & M)
Construct a rank-k matrix by restriction to the block cluster \(\tau \times \sigma\) without rank truncation from the global rank-k matrix M.
Note
The original rank-k global matrix M will not be modified.
Parameters
tau
sigma
M
Only when the formal rank of the current rank-k matrix is larger than zero, there will be actual initialization of component matrices and further restriction operation
Restrict the component matrix A of the original global rank-k matrix M to the cluster \(\tau\).
Restrict the component matrix B of the original global rank-k matrix M to the cluster \(\sigma\).
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, and RkMatrix< Number >::truncate_to_rank().
RkMatrix() [12/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const std::vector< types::global_dof_index > & tau, const std::vector< types::global_dof_index > & sigma, const size_type fixed_rank_k, const RkMatrix< Number > & M, const std::map< types::global_dof_index, size_t > & row_index_global_to_local_map_for_M, const std::map< types::global_dof_index, size_t > & col_index_global_to_local_map_for_M)
Construct a rank-k matrix by restriction to the block cluster \(\tau \times \sigma\) with rank truncation from the local rank-k matrix M.
Note
The original rank-k local matrix M will not be modified.
Parameters
tau
sigma
fixed_rank_k
M
row_index_global_to_local_map_for_M The map from the global row indices to the local indices of the matrix associated the H-matrix when first calling this recursive function.
col_index_global_to_local_map_for_M The map from the global column indices to the local indices of the matrix associated the H-matrix when first calling this recursive function.
Only when the formal rank of the current rank-k matrix is larger than zero, there will be actual initialization of component matrices and further restriction operation
Restrict the component matrix A of the original local rank-k matrix M to the cluster \(\tau\).
Restrict the component matrix B of the original local rank-k matrix M to the cluster \(\sigma\).
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, and RkMatrix< Number >::truncate_to_rank().
RkMatrix() [13/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const std::vector< types::global_dof_index > & tau, const std::vector< types::global_dof_index > & sigma, const RkMatrix< Number > & M, const std::map< types::global_dof_index, size_t > & row_index_global_to_local_map_for_M, const std::map< types::global_dof_index, size_t > & col_index_global_to_local_map_for_M)
Construct a rank-k matrix by restriction to the block cluster \(\tau \times \sigma\) without rank truncation from the local rank-k matrix M. The rank of the rank-k matrix to be constructed is initialized to be the minimum of its minimum matrix dimension and the rank of M.
Note
The original rank-k matrix M will not be modified.
Parameters
tau
sigma
M
row_index_global_to_local_map_for_M The map from the global row indices to the local indices of the matrix associated the H-matrix when first calling this recursive function.
col_index_global_to_local_map_for_M The map from the global column indices to the local indices of the matrix associated the H-matrix when first calling this recursive function.
Only when the formal rank of the current rank-k matrix is larger than zero, there will be actual initialization of component matrices and further restriction operation
Restrict the component A of the original local rank-k matrix M to the cluster \(\tau\).
Restrict the component B of the original local rank-k matrix M to the cluster \(\sigma\).
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, and RkMatrix< Number >::truncate_to_rank().
RkMatrix() [14/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const LAPACKFullMatrixExt< Number > & A, const LAPACKFullMatrixExt< Number > & B)
Construct a rank-k matrix from two component matrices.
Note
The formal rank of the rank-k matrix is set to the number of columns of matrix A or B. The rank of the rank-k matrix will not be calculated but temporarily set to the minimum dimension of the matrix. Hence we have \(\text{actual rank} \leq \text{rank} \leq \text{formal rank}\).
Parameters
A
B
The formal rank of the rank-k matrix is equal to the number of columns of A or B. Hence, we make an assertion about their equality.
RkMatrix() [15/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const size_type fixed_rank_k, const RkMatrix< Number > & M1, const RkMatrix< Number > & M2, bool is_horizontal_split)
Construct a rank-k matrix \(M\) from an agglomeration of two rank-k submatrices, \(M_1\) and \(M_2\), which have been obtained from either horizontal splitting or vertical splitting.
Parameters
fixed_rank_k
M1
M2
When both submatrices have zero ranks, the agglomerated matrix also has a zero rank. And there is nothing to be done.
When M1 has zero rank, the agglomeration operation is only an embedding of M2.
When M2 has zero rank, the agglomeration operation is only an embedding of M1.
Perform formatted addition of the two embedded matrices.
When both submatrices have zero ranks, the agglomerated matrix also has a zero rank. And there is nothing to be done.
When M1 has zero rank, the agglomeration operation is only an embedding of M2.
When M2 has zero rank, the agglomeration operation is only an embedding of M1.
Perform formatted addition of the two embedded matrices.
Here we only set the correct dimension of the agglomerated rank-k matrix.
References RkMatrix< Number >::add(), RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, and RkMatrix< Number >::truncate_to_rank().
RkMatrix() [16/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const size_type fixed_rank_k, const std::map< types::global_dof_index, size_t > & row_index_global_to_local_map_for_M, const std::map< types::global_dof_index, size_t > & col_index_global_to_local_map_for_M, const RkMatrix< Number > & M1, const std::vector< types::global_dof_index > & M1_tau_index_set, const std::vector< types::global_dof_index > & M1_sigma_index_set, const RkMatrix< Number > & M2, const std::vector< types::global_dof_index > & M2_tau_index_set, const std::vector< types::global_dof_index > & M2_sigma_index_set, bool is_horizontal_split)
Construct a rank-k matrix \(M\) from an agglomeration of two rank-k submatrices, \(M_1\) and \(M_2\), which have been obtained from either horizontal splitting or vertical splitting.
This method handles the case when the index sets of several child clusters are interwoven together into the index set of the parent cluster. This is based on the fact that during DoF support point coordinates based cluster tree partition, the continuity of the index set is not preserved.
Parameters
fixed_rank_k
row_index_global_to_local_map_for_M
col_index_global_to_local_map_for_M
M1
M1_tau_index_set
M1_sigma_index_set
M2
M2_tau_index_set
M2_sigma_index_set
is_horizontal_split
Note
Because the assembly of the two submatrices into the larger matrix depends on the global DoF indices, there is no need for a manual control of the assembly location and the procedures for both horizontal and vertical stacking cases are the same.
Make assertions about the sizes of row and column index global to local maps for M.
When both submatrices have zero ranks, the agglomerated matrix also has a zero rank. And there is nothing to be done.
When M1 has zero rank, the agglomeration operation is only an embedding of M2.
When M2 has zero rank, the agglomeration operation is only an embedding of M1.
Perform formatted addition of the two embedded matrices.
References RkMatrix< Number >::add(), RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, and RkMatrix< Number >::truncate_to_rank().
RkMatrix() [17/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const size_type fixed_rank_k, const RkMatrix< Number > & M11, const RkMatrix< Number > & M12, const RkMatrix< Number > & M21, const RkMatrix< Number > & M22, const Number rank_factor = 1.0)
Construct a rank-k matrix \(M\) from an agglomeration of four rank-k submatrices, \(M_{11}, M_{12}, M_{21}, M_{22}\).
\[ M = \begin{pmatrix} M_{11} & M_{12} \\ M_{21} & M_{22} \end{pmatrix} \]
Note
This method implements the operator \(\mathcal{T}_{r, {\rm pairw}}^{\mathcal{R}}\) in (2.13) in Hackbusch's \(\mathcal{H}\)-matrix book.
When all submatrices have zero ranks, the agglomerated matrix also has a zero rank. And there is nothing to be done.
Create a rank-k matrix which is an embedding of the submatrix. N.B. The embedding of a matrix does not change its rank.
At first, each matrix block is embedded into the large matrix by padding zeros to the component matrices A and B in a rank-k matrix. N.B. When perform rank-k matrix embedding, the formal rank instead of the real rank should be used since matrix row copy operation will be performed in which the formal rank will be involved as the number of columns.
Next, pairwise formatted addition will be applied successively to the four embedded matrices to achieve agglomeration.
Calculate the increased rank for pairwise formatted addition.
Count the total number of effective agglomeration operations to be performed.
Define a counter for the current agglomeration operation. When it is 1, directly embed the rank-k submatrix into the current rank-k matrix. When it is less than total_number_of_agglomerations and larger than 1, perform a formatted addition with a higher rank than the specified rank. When it is equal to total_number_of_agglomerations, perform a formatted addition with the specified rank.
Directly embed the matrix M11 into the current rank-k matrix.
Directly embed the matrix M12 into the current rank-k matrix.
Embed the matrix M12 then add it into the current rank-k matrix.
Directly embed the matrix M21 into the current rank-k matrix.
Embed the matrix M21 then add it into the current rank-k matrix.
Directly embed the matrix M22 into the current rank-k matrix.
Embed the matrix M22 then add it into the current rank-k matrix.
References RkMatrix< Number >::add(), RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, and RkMatrix< Number >::truncate_to_rank().
RkMatrix() [18/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const size_type fixed_rank_k, const std::map< types::global_dof_index, size_t > & row_index_global_to_local_map_for_M, const std::map< types::global_dof_index, size_t > & col_index_global_to_local_map_for_M, const RkMatrix< Number > & M11, const std::vector< types::global_dof_index > & M11_tau_index_set, const std::vector< types::global_dof_index > & M11_sigma_index_set, const RkMatrix< Number > & M12, const std::vector< types::global_dof_index > & M12_tau_index_set, const std::vector< types::global_dof_index > & M12_sigma_index_set, const RkMatrix< Number > & M21, const std::vector< types::global_dof_index > & M21_tau_index_set, const std::vector< types::global_dof_index > & M21_sigma_index_set, const RkMatrix< Number > & M22, const std::vector< types::global_dof_index > & M22_tau_index_set, const std::vector< types::global_dof_index > & M22_sigma_index_set, const Number rank_factor = 1.0)
Construct a rank-k matrix \(M\) from an agglomeration of four rank-k submatrices, \(M_{11}, M_{12}, M_{21}, M_{22}\).
\[ M = \begin{pmatrix} M_{11} & M_{12} \\ M_{21} & M_{22} \end{pmatrix} \]
Note
This method implements the operator \(\mathcal{T}_{r, {\rm pairw}}^{\mathcal{R}}\) in (2.13) in Hackbusch's \(\mathcal{H}\)-matrix book.
This method handles the case when the index sets of several child clusters are interwoven together into the index set of the parent cluster. This is based on the fact that during the cluster tree partition based on DoF support point coordinates, the continuity of the index set is not preserved.
Make assertions about the compatibility of number of rows and columns of the submatrices.
Make assertions about the equality of cluster index sets of submatrices.
Make assertions about the sizes of row and column index global-to-local maps for M.
Make assertions about the submatrix sizes and associated index sets.
When all submatrices have zero ranks, the agglomerated matrix also has a zero rank. And there is nothing to be done.
Create a rank-k matrix which is an embedding of the submatrix. N.B. The embedding of a matrix does not change its rank and formal rank.
At first, each matrix block is embedded into the large matrix by padding zeros to the component matrices A and B in a rank-k matrix. N.B. When perform rank-k matrix embedding, the formal rank instead of the real rank should be used since matrix row copy operation will be performed in which the formal rank will be involved as the number of columns.
Next, pairwise formatted addition will be applied successively to the four embedded matrices to achieve agglomeration.
Calculate the increased rank for pairwise formatted addition.
Count the total number of effective agglomeration operations to be performed.
Define a counter for the current agglomeration operation. When it is 1, directly embed the rank-k submatrix into the current rank-k matrix. When it is less than total_number_of_agglomerations and larger than 1, perform a formatted addition with a higher rank than the specified rank. When it is equal to total_number_of_agglomerations, perform a formatted addition with the specified rank.
Directly embed the matrix M11 into the current rank-k matrix.
Directly embed the matrix M12 into the current rank-k matrix.
Embed the matrix M12 then add it into the current rank-k matrix.
Directly embed the matrix M21 into the current rank-k matrix.
Embed the matrix M21 then add it into the current rank-k matrix.
Directly embed the matrix M22 into the current rank-k matrix.
Embed the matrix M22 then add it into the current rank-k matrix.
References RkMatrix< Number >::add(), RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, and RkMatrix< Number >::truncate_to_rank().
RkMatrix() [19/19]
template<typename Number > RkMatrix< Number >::RkMatrix (const RkMatrix< Number > & matrix)
Copy constructor.
Member Function Documentation
add() [1/12]
template<typename Number > void RkMatrix< Number >::add (RkMatrix< Number > & M, const RkMatrix< Number > & M2) const
Perform the addition of two rank-k matrices \(M = M_1 + M_2\) by juxtaposition without rank truncation, where \(M_1\) is the current matrix.
Let \(M_1 = A_1 B_1^T\) and \(M_2 = A_2 B_2^T\). Their addition without truncation is a juxtaposition of the components of \(M_1\) and \(M_2\). Assume \(M = AB^T\), then \(A = [A_1 A_2]\) and \(B = [B_1 B_2]\). Its rank \(r \leq r_1 + r_2\). Also note that the value of the class member M may be just formal, i.e. the actual matrix rank is smaller than it.
Parameters
M
M2
fixed_rank_k
Stack the components of A and B.
References RkMatrix< Number >::rank.
Referenced by RkMatrix< Number >::add(), RkMatrix< Number >::assemble_from_rkmatrix(), main(), and RkMatrix< Number >::RkMatrix().
add() [2/12]
template<typename Number > void RkMatrix< Number >::add (RkMatrix< Number > & M, const Number m2, const RkMatrix< Number > & M2) const
Perform the addition of two rank-k matrices \(M = M_1 + m_2 M_2\) with a factor \(m_2\) multiplied to \(M_2\). There is no rank truncation.
Stack the components of A and B.
Multiply the factor with M2.A.
References RkMatrix< Number >::rank.
add() [3/12]
template<typename Number > void RkMatrix< Number >::add (const RkMatrix< Number > & M1)
Perform the addition of two rank-k matrices \(M = M + M_1\) by juxtaposition without rank truncation, where \(M\) is the current matrix.
Parameters
M1
Stack the components of A and B.
References RkMatrix< Number >::rank.
add() [4/12]
template<typename Number > void RkMatrix< Number >::add (const Number m1, const RkMatrix< Number > & M1)
Perform the addition of two rank-k matrices \(M = M + m_1 M_1\) with a factor \(m_1\) multiplied to \(M_1\). There is no rank truncation.
Parameters
M1
Stack the components of A and B.
Multiply the factor m1 with M1.A.
References RkMatrix< Number >::rank.
add() [5/12]
template<typename Number > void RkMatrix< Number >::add (RkMatrix< Number > & M, const RkMatrix< Number > & M2, const size_type fixed_rank_k) const
Perform the formatted addition of two rank-k matrices, \(M = M_1 + M_2\). The resulted rank-k matrix M will be truncated to the fixed rank fixed_rank_k.
Perform the addition via a simple juxtaposition of matrix components. Then rank truncation is carried out.
References RkMatrix< Number >::add(), and RkMatrix< Number >::truncate_to_rank().
add() [6/12]
template<typename Number > void RkMatrix< Number >::add (RkMatrix< Number > & M, const RkMatrix< Number > & M2, const size_type fixed_rank_k, LAPACKFullMatrixExt< Number > & C, LAPACKFullMatrixExt< Number > & D) const
Perform the formatted addition of two rank-k matrices, \(M = M_1 + M_2\). The resulted rank-k matrix M will be truncated to the fixed rank fixed_rank_k. The truncation error is returned as the product \(CD^T\).
Parameters
M
M2
fixed_rank_k
C
D
Perform the addition via a simple juxtaposition of matrix components. Then rank truncation is carried out.
References RkMatrix< Number >::add(), and RkMatrix< Number >::truncate_to_rank().
add() [7/12]
template<typename Number > void RkMatrix< Number >::add (RkMatrix< Number > & M, const Number m2, const RkMatrix< Number > & M2, const size_type fixed_rank_k) const
Perform the formatted addition of two rank-k matrices, \(M = M_1 + m_2 M_2\) with a factor \(m_2\) multiplied to \(M_2\). The resulted rank-k matrix M will be truncated to the fixed rank fixed_rank_k.
Perform the addition via a simple juxtaposition of matrix components. Then rank truncation is carried out.
References RkMatrix< Number >::add(), and RkMatrix< Number >::truncate_to_rank().
add() [8/12]
template<typename Number > void RkMatrix< Number >::add (RkMatrix< Number > & M, const Number m2, const RkMatrix< Number > & M2, const size_type fixed_rank_k, LAPACKFullMatrixExt< Number > & C, LAPACKFullMatrixExt< Number > & D) const
Perform the formatted addition of two rank-k matrices, \(M = M_1 + m_2 M_2\) with a factor \(m_2\) multiplied to \(M_2\). The resulted rank-k matrix M will be truncated to the fixed rank fixed_rank_k. The truncation error is returned as the product \(CD^T\).
Parameters
M
m2
M2
fixed_rank_k
C
D
Perform the addition via a simple juxtaposition of matrix components. Then rank truncation is carried out.
References RkMatrix< Number >::add(), and RkMatrix< Number >::truncate_to_rank().
add() [9/12]
template<typename Number > void RkMatrix< Number >::add (const RkMatrix< Number > & M1, const size_type fixed_rank_k)
Perform the formatted addition of two rank-k matrices, \(M = M + M_1\). M_1 is added to the current matrix itself. The resulted rank-k matrix M will be truncated to the fixed rank fixed_rank_k.
Perform the addition via a simple juxtaposition of matrix components. Then rank truncation is carried out.
References RkMatrix< Number >::add(), and RkMatrix< Number >::truncate_to_rank().
add() [10/12]
template<typename Number > void RkMatrix< Number >::add (const RkMatrix< Number > & M1, const size_type fixed_rank_k, LAPACKFullMatrixExt< Number > & C, LAPACKFullMatrixExt< Number > & D)
Perform the formatted addition of two rank-k matrices, \(M = M + M_1\). M_1 is added to the current matrix itself. The resulted rank-k matrix M will be truncated to the fixed rank fixed_rank_k. The truncation error is returned as the product \(CD^T\).
Parameters
M1
fixed_rank_k
C
D
Perform the addition via a simple juxtaposition of matrix components. Then rank truncation is carried out.
References RkMatrix< Number >::add(), and RkMatrix< Number >::truncate_to_rank().
add() [11/12]
template<typename Number > void RkMatrix< Number >::add (const Number m1, const RkMatrix< Number > & M1, const size_type fixed_rank_k)
Perform the formatted addition of two rank-k matrices, \(M = M + m_1 M_1\) with factor \(m_1\) multiplied to \(M_1\). M_1 is added to the current matrix itself. The resulted rank-k matrix M will be truncated to the fixed rank fixed_rank_k.
Perform the addition via a simple juxtaposition of matrix components. Then rank truncation is carried out.
References RkMatrix< Number >::add(), and RkMatrix< Number >::truncate_to_rank().
add() [12/12]
template<typename Number > void RkMatrix< Number >::add (const Number m1, const RkMatrix< Number > & M1, const size_type fixed_rank_k, LAPACKFullMatrixExt< Number > & C, LAPACKFullMatrixExt< Number > & D)
Perform the formatted addition of two rank-k matrices, \(M = M + m_1 M_1\) with factor \(m_1\) multiplied to \(M_1\). M_1 is added to the current matrix itself. The resulted rank-k matrix M will be truncated to the fixed rank fixed_rank_k. The truncation error is returned as the product \(CD^T\).
Parameters
m1
M1
fixed_rank_k
C
D
Perform the addition via a simple juxtaposition of matrix components. Then rank truncation is carried out.
References RkMatrix< Number >::add(), and RkMatrix< Number >::truncate_to_rank().
assemble_from_rkmatrix() [1/2]
template<typename Number > void RkMatrix< Number >::assemble_from_rkmatrix (const std::map< types::global_dof_index, size_t > & row_index_global_to_local_map, const std::map< types::global_dof_index, size_t > & col_index_global_to_local_map, const RkMatrix< Number > & M, const std::vector< types::global_dof_index > & M_tau_index_set, const std::vector< types::global_dof_index > & M_sigma_index_set, const size_type fixed_rank_k)
Assemble the smaller rank-k matrix M into the current rank-k matrix with respect to the specified row_index_global_to_local_map and col_index_global_to_local_map.
When perform rank-k matrix embedding, the formal rank instead of the real rank should be used since matrix row copy operation will be performed in which the formal rank will be involved as the number of columns.
Only when the rank-k matrix M has a rank larger than zero, the assembly operation will take place.
References RkMatrix< Number >::add(), RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, and RkMatrix< Number >::rank.
assemble_from_rkmatrix() [2/2]
template<typename Number > void RkMatrix< Number >::assemble_from_rkmatrix (const std::map< types::global_dof_index, size_t > & row_index_global_to_local_map, const std::map< types::global_dof_index, size_t > & col_index_global_to_local_map, const RkMatrix< Number > & M, const std::vector< types::global_dof_index > & M_tau_index_set, const std::vector< types::global_dof_index > & M_sigma_index_set, const size_type fixed_rank_k, LAPACKFullMatrixExt< Number > & C, LAPACKFullMatrixExt< Number > & D)
Assemble the smaller rank-k matrix M into the current rank-k matrix with respect to the specified row_index_global_to_local_map and col_index_global_to_local_map. The truncation error is returned as the product \(CD^T\).
Parameters
row_index_global_to_local_map
col_index_global_to_local_map
M
M_tau_index_set
M_sigma_index_set
fixed_rank_k
C
D
When perform rank-k matrix embedding, the formal rank instead of the real rank should be used since matrix row copy operation will be performed in which the formal rank will be involved as the number of columns.
Only when the rank-k matrix M has a rank larger than zero, the assembly operation will take place.
References RkMatrix< Number >::add(), RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, and RkMatrix< Number >::rank.
calc_rank_upper_bound()
template<typename Number > void RkMatrix< Number >::calc_rank_upper_bound ()
Calculate the upper bound of the matrix rank, which is \(\min\{{\rm rank}(A), {\rm rank}(B), rank\}\).
References RkMatrix< Number >::rank.
convertToFullMatrix()
template<typename Number > void RkMatrix< Number >::convertToFullMatrix (LAPACKFullMatrixExt< Number > & matrix) const
Convert an rank-k matrix to a full matrix.
Parameters
matrix
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, and RkMatrix< Number >::n.
Referenced by main(), and RkMatrix< Number >::restrictToFullMatrix().
get_A() [1/2]
template<typename Number > LAPACKFullMatrixExt< Number > & RkMatrix< Number >::get_A ()
Get the reference to the component matrix A.
Returns
get_A() [2/2]
template<typename Number > const LAPACKFullMatrixExt< Number > & RkMatrix< Number >::get_A () const
Get the reference to the component matrix A (const version).
Returns
get_B() [1/2]
template<typename Number > LAPACKFullMatrixExt< Number > & RkMatrix< Number >::get_B ()
Get the reference to the component matrix B.
Returns
get_B() [2/2]
template<typename Number > const LAPACKFullMatrixExt< Number > & RkMatrix< Number >::get_B () const
Get the reference to the component matrix B (const version).
Returns
get_formal_rank()
template<typename Number > RkMatrix< Number >::size_type RkMatrix< Number >::get_formal_rank () const
Get the formal rank of the rank-k matrix.
Returns
References RkMatrix< Number >::formal_rank.
get_m()
template<typename Number > RkMatrix< Number >::size_type RkMatrix< Number >::get_m () const
Get the number of rows.
Returns
References RkMatrix< Number >::m.
Referenced by HMatrix< spacedim, Number >::add().
get_n()
template<typename Number > RkMatrix< Number >::size_type RkMatrix< Number >::get_n () const
Get the number of columns.
Returns
References RkMatrix< Number >::n.
Referenced by HMatrix< spacedim, Number >::add().
get_rank()
template<typename Number > RkMatrix< Number >::size_type RkMatrix< Number >::get_rank () const
Get the rank of the rank-k matrix.
Returns
References RkMatrix< Number >::rank.
operator=()
template<typename Number > RkMatrix< Number > & RkMatrix< Number >::operator= (const RkMatrix< Number > & matrix)
Assignment operator.
Parameters
matrix
Returns
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, and RkMatrix< Number >::rank.
print_formatted()
template<typename Number > void RkMatrix< Number >::print_formatted (std::ostream & out, const unsigned int precision = 3, const bool scientific = true, const unsigned int width = 0, const char * zero_string = "0", const double denominator = 1., const double threshold = 0.) const
Print a RkMatrix.
Parameters
out
precision
scientific
width
zero_string
denominator
threshold
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, and RkMatrix< Number >::rank.
Referenced by main().
print_formatted_to_mat()
template<typename Number > void RkMatrix< Number >::print_formatted_to_mat (std::ostream & out, const std::string & name, const unsigned int precision = 8, const bool scientific = true, const unsigned int width = 0, const char * zero_string = "0", const double denominator = 1., const double threshold = 0.) const
Print a RkMatrix into Octave mat format.
Parameters
out
name
precision
scientific
width
zero_string
denominator
threshold
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, and RkMatrix< Number >::rank.
Referenced by main().
reinit()
template<typename Number > void RkMatrix< Number >::reinit (const size_type m, const size_type n, const size_type fixed_rank_k)
Reinitialize a rank-k matrix with specified dimension and rank. By default, all matrix entries are initialized to zero.
Parameters
m
n
fixed_rank_k
omit_zeroing_entries
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, and RkMatrix< Number >::rank.
Referenced by h_rk_mmult(), h_rk_mTmult(), rk_h_mmult(), and rk_h_mTmult().
restrictToFullMatrix() [1/2]
template<typename Number > void RkMatrix< Number >::restrictToFullMatrix (const std::vector< types::global_dof_index > & tau, const std::vector< types::global_dof_index > & sigma, LAPACKFullMatrixExt< Number > & matrix) const
Restrict a global rank-k matrix to a full matrix defined on the block cluster \(\tau \times \sigma\).
References RkMatrix< Number >::convertToFullMatrix().
Referenced by HMatrix< spacedim, Number >::_distribute_sigma_r_and_f_to_leaves(), HMatrix< spacedim, Number >::add(), and main().
restrictToFullMatrix() [2/2]
template<typename Number > void RkMatrix< Number >::restrictToFullMatrix (const std::vector< types::global_dof_index > & tau, const std::vector< types::global_dof_index > & sigma, const std::map< types::global_dof_index, size_t > & row_index_global_to_local_map_for_rk, const std::map< types::global_dof_index, size_t > & col_index_global_to_local_map_for_rk, LAPACKFullMatrixExt< Number > & matrix) const
Restrict a local rank-k matrix to a full matrix defined on the block cluster \(\tau \times \sigma\).
Parameters
tau
sigma
row_index_global_to_local_map_for_rk
col_index_global_to_local_map_for_rk
matrix
References RkMatrix< Number >::convertToFullMatrix().
truncate_to_rank() [1/2]
template<typename Number > void RkMatrix< Number >::truncate_to_rank (size_type new_rank)
Truncate the RkMatrix to new_rank.
Note
This method implements the operator \(\mathcal{T}_{r \leftarrow s}^{\mathcal{R}}\) in (7.4) in Hackbusch's \(\mathcal{H}\)-matrix book. If the actual rank of the matrix is less than the specified new_rank, i.e. rank deficient, the matrix will be truncated to its actual rank.
Parameters
new_rank
Only when the current rank-k matrix and the given new rank have nonzero rank, it is meaningful to perform the rank truncation.
Work flow introduction: Use QR decomposition to perform the rank truncation.
Since the initial matrix may not have the correct rank, even though its rank is larger than zero, its actual rank may be less or even zero. Therefore, it is possible that the returned rank from the above execution of reduced_svd_on_AxBT may be zero. Therefore, it needs a special treatment here.
Adopt right associativity when the matrix is long.
Adopt left associativity when the matrix is wide.
Update the formal rank.
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, LAPACKFullMatrixExt< Number >::reduced_svd_on_AxBT(), LAPACKFullMatrixExt< Number >::scale_columns(), LAPACKFullMatrixExt< Number >::scale_rows(), and LAPACKFullMatrixExt< Number >::transpose().
Referenced by RkMatrix< Number >::add(), main(), and RkMatrix< Number >::RkMatrix().
truncate_to_rank() [2/2]
template<typename Number > void RkMatrix< Number >::truncate_to_rank (size_type new_rank, LAPACKFullMatrixExt< Number > & C, LAPACKFullMatrixExt< Number > & D)
Truncate the RkMatrix to new_rank with the error matrices returned.
Note
This method implements the operator \(\mathcal{T}_{r \leftarrow s}^{\mathcal{R}}\) in (7.4) in Hackbusch's \(\mathcal{H}\)-matrix book. If the actual rank of the matrix is less than the specified new_rank, i.e. rank deficient, the matrix will be truncated to its actual rank.
Parameters
new_rank
Only when the current rank-k matrix and the given new rank have nonzero rank, it is meaningful to perform the rank truncation.
Work flow introduction: Use QR decomposition to perform the rank truncation.
Since the initial matrix may not have the correct rank, even though its rank is larger than zero, its actual rank may be less or even zero. Therefore, it is possible that the returned rank from the above execution of reduced_svd_on_AxBT may be zero. Therefore, it needs a special treatment here.
Adopt right associativity when the matrix is long.
Adopt left associativity when the matrix is wide.
Update the formal rank.
If the original matrix's rank is zero, the error matrices should be zero matrices.
If the original matrix's rank is nonzero but it is to be truncated to zero rank, the error matrices should be directly copied from \(A\) and \(B\).
Balance the Frobenius norm of C and D.
References RkMatrix< Number >::formal_rank, RkMatrix< Number >::m, RkMatrix< Number >::n, RkMatrix< Number >::rank, LAPACKFullMatrixExt< Number >::reduced_svd_on_AxBT(), LAPACKFullMatrixExt< Number >::scale_columns(), LAPACKFullMatrixExt< Number >::scale_rows(), and LAPACKFullMatrixExt< Number >::transpose().
Tvmult()
template<typename Number > void RkMatrix< Number >::Tvmult (Vector< Number > & y, const Vector< Number > & x, const bool adding = false) const
Calculate matrix-vector multiplication as \(y = B A^T x\) or \(y = y + B A^T x\).
Parameters
y
x
adding
Only when the rank is larger than zero, the multiplication will be performed.
The vector storing \(B^T x\)
The result vector \(y\) will be overwritten by zeros.
References RkMatrix< Number >::formal_rank, and RkMatrix< Number >::rank.
vmult()
template<typename Number > void RkMatrix< Number >::vmult (Vector< Number > & y, const Vector< Number > & x, const bool adding = false) const
Calculate matrix-vector multiplication as \(y = A B^T x\) or \(y = y + A B^T x\).
Parameters
y
x
adding
Only when the rank is larger than zero, the multiplication will be performed.
The vector storing \(B^T x\)
The result vector \(y\) will be overwritten by zeros.
References RkMatrix< Number >::formal_rank, and RkMatrix< Number >::rank.
Member Data Documentation
formal_rank
template<typename Number = double> size_type RkMatrix< Number >::formal_rank private
Formal matrix rank, which is equal to the number of columns of A or B, i.e. A.n or B.n.
Referenced by RkMatrix< Number >::assemble_from_rkmatrix(), RkMatrix< Number >::convertToFullMatrix(), RkMatrix< Number >::get_formal_rank(), h_rk_mmult(), h_rk_mTmult(), RkMatrix< Number >::operator=(), RkMatrix< Number >::print_formatted(), RkMatrix< Number >::print_formatted_to_mat(), print_rkmatrix_to_mat(), RkMatrix< Number >::reinit(), rk_h_mmult(), rk_h_mTmult(), RkMatrix< Number >::RkMatrix(), RkMatrix< Number >::truncate_to_rank(), RkMatrix< Number >::Tvmult(), and RkMatrix< Number >::vmult().
m
template<typename Number = double> size_type RkMatrix< Number >::m private
Total number of rows.
Referenced by RkMatrix< Number >::assemble_from_rkmatrix(), RkMatrix< Number >::convertToFullMatrix(), RkMatrix< Number >::get_m(), h_rk_mmult(), h_rk_mTmult(), RkMatrix< Number >::operator=(), RkMatrix< Number >::print_formatted(), RkMatrix< Number >::print_formatted_to_mat(), print_rkmatrix_to_mat(), RkMatrix< Number >::reinit(), rk_h_mmult(), rk_h_mTmult(), RkMatrix< Number >::RkMatrix(), and RkMatrix< Number >::truncate_to_rank().
n
template<typename Number = double> size_type RkMatrix< Number >::n private
Total number of columns
Referenced by RkMatrix< Number >::assemble_from_rkmatrix(), RkMatrix< Number >::convertToFullMatrix(), RkMatrix< Number >::get_n(), h_rk_mmult(), h_rk_mTmult(), RkMatrix< Number >::operator=(), RkMatrix< Number >::print_formatted(), RkMatrix< Number >::print_formatted_to_mat(), print_rkmatrix_to_mat(), RkMatrix< Number >::reinit(), rk_h_mmult(), rk_h_mTmult(), RkMatrix< Number >::RkMatrix(), and RkMatrix< Number >::truncate_to_rank().
rank
template<typename Number = double> size_type RkMatrix< Number >::rank private
Matrix rank, which is either the actual matrix rank or the minimum of m, n and A.n (or B.n). Actually, this is an upper bound of the actual matrix rank.
Referenced by RkMatrix< Number >::add(), RkMatrix< Number >::assemble_from_rkmatrix(), RkMatrix< Number >::calc_rank_upper_bound(), RkMatrix< Number >::get_rank(), RkMatrix< Number >::operator=(), RkMatrix< Number >::print_formatted(), RkMatrix< Number >::print_formatted_to_mat(), print_rkmatrix_to_mat(), RkMatrix< Number >::reinit(), RkMatrix< Number >::RkMatrix(), RkMatrix< Number >::truncate_to_rank(), RkMatrix< Number >::Tvmult(), and RkMatrix< Number >::vmult().
The documentation for this class was generated from the following file:
/home/jihuan/Projects/deal.ii/program/dealii-9.1.1/examples/laplace-bem/include/rkmatrix.h