laplace-bem: LaplaceBEM::BEMValues< dim, spacedim, RangeNumberType > Class Template Reference
LaplaceBEM::BEMValues< dim, spacedim, RangeNumberType > Class Template Reference
Public Member Functions
BEMValues (const FiniteElement< dim, spacedim > &kx_fe, const FiniteElement< dim, spacedim > &ky_fe, const QGauss< 4 > &quad_rule_for_same_panel, const QGauss< 4 > &quad_rule_for_common_edge, const QGauss< 4 > &quad_rule_for_common_vertex, const QGauss< 4 > &quad_rule_for_regular)
BEMValues (const BEMValues< dim, spacedim, RangeNumberType > &bem_values)
void fill_shape_value_tables ()
void fill_shape_grad_matrix_tables ()
Public Attributes
const FiniteElement< dim, spacedim > & kx_fe
const FiniteElement< dim, spacedim > & ky_fe
const QGauss< 4 > & quad_rule_for_same_panel
const QGauss< 4 > & quad_rule_for_common_edge
const QGauss< 4 > & quad_rule_for_common_vertex
const QGauss< 4 > & quad_rule_for_regular
Table< 3, RangeNumberType > kx_shape_value_table_for_same_panel
Table< 3, RangeNumberType > ky_shape_value_table_for_same_panel
Table< 3, RangeNumberType > kx_shape_value_table_for_common_edge
Table< 3, RangeNumberType > ky_shape_value_table_for_common_edge
Table< 3, RangeNumberType > kx_shape_value_table_for_common_vertex
Table< 3, RangeNumberType > ky_shape_value_table_for_common_vertex
Table< 3, RangeNumberType > kx_shape_value_table_for_regular
Table< 3, RangeNumberType > ky_shape_value_table_for_regular
Table< 2, FullMatrix< RangeNumberType > > kx_shape_grad_matrix_table_for_same_panel
Table< 2, FullMatrix< RangeNumberType > > ky_shape_grad_matrix_table_for_same_panel
Table< 2, FullMatrix< RangeNumberType > > kx_shape_grad_matrix_table_for_common_edge
Table< 2, FullMatrix< RangeNumberType > > ky_shape_grad_matrix_table_for_common_edge
Table< 2, FullMatrix< RangeNumberType > > kx_shape_grad_matrix_table_for_common_vertex
Table< 2, FullMatrix< RangeNumberType > > ky_shape_grad_matrix_table_for_common_vertex
Table< 2, FullMatrix< RangeNumberType > > kx_shape_grad_matrix_table_for_regular
Table< 2, FullMatrix< RangeNumberType > > ky_shape_grad_matrix_table_for_regular
Protected Member Functions
void init_shape_value_tables ()
void init_shape_grad_matrix_tables ()
Constructor & Destructor Documentation
BEMValues()
template<int dim, int spacedim, typename RangeNumberType > LaplaceBEM::BEMValues< dim, spacedim, RangeNumberType >::BEMValues (const BEMValues< dim, spacedim, RangeNumberType > & bem_values)
Copy constructor for class BEMValues.
Parameters
bem_values
References LaplaceBEM::bem_shape_grad_matrices_common_edge(), LaplaceBEM::bem_shape_grad_matrices_common_vertex(), LaplaceBEM::bem_shape_grad_matrices_regular(), LaplaceBEM::bem_shape_grad_matrices_same_panel(), LaplaceBEM::bem_shape_values_common_edge(), LaplaceBEM::bem_shape_values_common_vertex(), LaplaceBEM::bem_shape_values_regular(), and LaplaceBEM::bem_shape_values_same_panel().
The documentation for this class was generated from the following file:
/home/jihuan/Projects/deal.ii/program/dealii-9.1.1/examples/laplace-bem/include/laplace_bem.h