laplace-bem: /home/jihuan/Projects/deal.ii/program/dealii-9.1.1/examples/laplace-bem/tests/cluster-diameter/cluster-diameter.cc File Reference
cluster-diameter.cc File Reference
Hierarchical matrices
This files verifies the cluster diameter and pair-wise distance calculation using a 3x3 grid in a square.
#include <deal.II/base/logstream.h>
#include <deal.II/base/point.h>
#include <deal.II/fe/fe_q.h>
#include <deal.II/fe/mapping_q_generic.h>
#include <deal.II/grid/grid_generator.h>
#include <deal.II/grid/grid_in.h>
#include <deal.II/grid/grid_out.h>
#include <simple_bounding_box.h>
#include <fstream>
#include "cluster_tree.h"
#include "debug_tools.h"
Functions
int main ()
Detailed Description
This files verifies the cluster diameter and pair-wise distance calculation using a 3x3 grid in a square.
Date
2021-04-25
Author
Jihuan Tian
Function Documentation
main()
int main ()
Initialize deal.ii log stream.
Generate the 3x3 grid in a 2D square.
Save the mesh to a file for visualization.
Create the Lagrangian finite element.
Create a DoFHandler, which is associated with the triangulation and distributed with the finite element.
Create the mapping object, which is required in generating the map from DoF indices to support points.
Generate a list of all DoF indices.
Print the coordinates of all support points.
Write DoF indices at each support point.
Calculate the average mesh cell size at each support point.
Initialize the cluster tree \(T(I)\) and \(T(J)\) for all the DoF indices.
Partition the cluster tree.
Print the whole cluster trees.
Get the cluster containing DoF indices [0 1 2 3].
Get the cluster containing DoF indices [10, 11, 14, 15].
References map_dofs_to_average_cell_size(), map_dofs_to_max_cell_size(), map_dofs_to_min_cell_size(), and print_support_point_info().