laplace-bem: /home/jihuan/Projects/deal.ii/program/dealii-9.1.1/examples/laplace-bem/include/generic_functors.h File Reference
generic_functors.h File Reference
This header file contains a set of self-defined generic functors.
#include <deal.II/base/exceptions.h>
#include <deal.II/base/types.h>
#include <deal.II/lac/lapack_support.h>
#include <forward_list>
#include <iterator>
#include <map>
#include <vector>
Typedefs
using size_type = std::make_unsigned< types::blas_int >::type
Functions
template<typename InputIterator , typename T >
InputIterator find_pointer_data (InputIterator first, InputIterator last, const T *value_pointer)
void build_index_set_global_to_local_map (const std::vector< dealii::types::global_dof_index > &index_set_as_local_to_global_map, std::map< dealii::types::global_dof_index, size_t > &global_to_local_map)
template<typename VectorType >
void permute_vector_by_ipiv (VectorType &v, const std::vector< dealii::types::blas_int > &ipiv)
template<typename T >
size_type size (const std::forward_list< T > &fl)
template<typename T >
T & value_at (std::forward_list< T > &fl, const size_type i)
template<typename T >
const T & value_at (const std::forward_list< T > &fl, const size_type i)
template<typename T >
void erase_at (std::forward_list< T > &fl, const size_type i)
Detailed Description
This header file contains a set of self-defined generic functors.
Date
2021-07-20
Author
Jihuan Tian
Function Documentation
build_index_set_global_to_local_map()
void build_index_set_global_to_local_map (const std::vector< dealii::types::global_dof_index > & index_set_as_local_to_global_map, std::map< dealii::types::global_dof_index, size_t > & global_to_local_map)
Build a map from global indices to local indices based on the given index set, which is actually a map from local indices to global indices.
Parameters
index_set_as_local_to_global_map
global_to_local_map
Referenced by convertHMatBlockToRkMatrix(), f_h_mmult(), f_h_mTmult(), find_pointer_data(), h_f_mmult(), h_f_mTmult(), h_rk_mmult(), h_rk_mTmult(), InitAndCreateHMatrixChildren(), InitAndCreateHMatrixChildrenWithoutAlloc(), main(), rk_h_mmult(), and rk_h_mTmult().
erase_at()
template<typename T > void erase_at (std::forward_list< T > & fl, const size_type i)
Erase the i'th element of the std::forward_list.
Parameters
fl
i
Referenced by IdeoBEM::random_select_ref_column(), and IdeoBEM::random_select_ref_row().
find_pointer_data()
template<typename InputIterator , typename T > InputIterator find_pointer_data (InputIterator first, InputIterator last, const T * value_pointer)
Find the pointer in a list of pointers of the same type. The comparison is based on the data being pointed instead of the pointer addresses.
Parameters
first
last
value_pointer
Returns
N.B. Here we use (*first) to get the pointer stored in the container. Then use (*(*first)) to get the data associated with this pointer.
References build_index_set_global_to_local_map().
Referenced by HMatrix< spacedim, Number >::coarsen_to_partition(), and prune_to_partition_recursion().
permute_vector_by_ipiv()
template<typename VectorType > void permute_vector_by_ipiv (VectorType & v, const std::vector< dealii::types::blas_int > & ipiv)
Permute a vector according to the permutation vector ipiv obtained from an LU factorization.
Parameters
v
ipiv The vector storing the row permutation obtained from an LU factorization. The row indices stored in ipiv starts from 1 instead of 0.
Referenced by LAPACKFullMatrixExt< Number >::solve_by_forward_substitution().
size()
template<typename T > size_type size (const std::forward_list< T > & fl)
Get the size of a std::forward_list.
Parameters
fl
Returns
Referenced by IdeoBEM::random_select_ref_column(), and IdeoBEM::random_select_ref_row().
value_at() [1/2]
template<typename T > T& value_at (std::forward_list< T > & fl, const size_type i)
Get the reference to the i'th element of the std::forward_list.
Parameters
fl
index
Returns
Referenced by IdeoBEM::random_select_ref_column(), and IdeoBEM::random_select_ref_row().
value_at() [2/2]
template<typename T > const T& value_at (const std::forward_list< T > & fl, const size_type i)
Get the const reference to the i'th element of the std::forward_list.
Parameters
fl
index
Returns