laplace-bem: Hierarchical matrices
Hierarchical matrices
Implementation of hierarchical matrix data structure and algebraic operations.
Files
file block_cluster.h
Implementation of the class BlockCluster.
file block_cluster_tree.h
Implementation of the class BlockClusterTree.
file cluster.h
Implementation of the class Cluster.
file hmatrix.h
Definition of hierarchical matrix.
file rkmatrix.h
Definition of rank-k matrix.
file tree.h
Implementation of the classes for binary tree node, general tree node and functions for manipulating the trees constructed from these nodes.
file block-cluster-tree.cc
This files verifies the admissible block cluster partition.
file cluster-diameter.cc
This files verifies the cluster diameter and pair-wise distance calculation using a 3x3 grid in a square.
file cluster-tree-hp.cc
Test the construction of a \(\mathcal{H}^p\) cluster tree.
file hmatrix-add-formatted.cc
Verify formatted addition of two \(\mathcal{H}\)-matrices.
file hmatrix-add-formatted-with-factor.cc
Verify formatted addition of two \(\mathcal{H}\)-matrices \(C = A + b B\).
file hmatrix-add-rkmatrix-into-new-hmatrix.cc
Verify the addition of a rank-k matrix and an \(\mathcal{H}\)-matrix into a new \(\mathcal{H}\)-matrix.
file hmatrix-add-rkmatrix-into-new-hmatrix-with-factor.cc
Verify the addition of a rank-k matrix multiplied by a factor and an \(\mathcal{H}\)-matrix into a new \(\mathcal{H}\)-matrix.
file hmatrix-backward-substitution.cc
Verify backward substitution of an upper triangle \(\mathcal{H}\)-matrix. The block cluster tree partition structure is fine non-tensor product.
file hmatrix-backward-substitution-coarse-ntp.cc
Verify backward substitution of an upper triangle \(\mathcal{H}\)-matrix. The block cluster tree partition structure is coarse non-tensor product.
file hmatrix-backward-substitution-unit-diag.cc
Verify backward substitution of an unit upper triangle \(\mathcal{H}\)-matrix. The block cluster tree partition structure is fine non-tensor product.
file hmatrix-bct-struct-with-rank.cc
Visualize the block cluster tree structure of an H-matrix with displayed rank.
file hmatrix-block-triangular-backward-substitution.cc
Verify backward substitution of an upper block triangle \(\mathcal{H}\)-matrix. The block cluster tree partition structure is fine non-tensor product.
file hmatrix-block-triangular-backward-substitution-unit-diag.cc
Verify backward substitution of an unit upper block triangle \(\mathcal{H}\)-matrix. The block cluster tree partition structure is fine non-tensor product.
file hmatrix-check-parent-and-submatrix-index.cc
Check the parent and submatrix_index member variables of \(\mathcal{H}\)-matrix.
file hmatrix-cholesky-backward-substitution.cc
Verify backward substitution for the lower triangle \(\mathcal{H}\)-matrix obtained from Cholesky decomposition. The block cluster tree partition structure is fine non-tensor product.
file hmatrix-cholesky-transpose-forward-substitution-matrix-valued.cc
Verify matrix-valued forward substitution of the transpose of a upper triangular \(\mathcal{H}\)-matrix.
file hmatrix-coarsening.cc
Coarsen a H-matrix to its subtree.
file hmatrix-find-diagonal-blocks.cc
Find the diagonal blocks related to the current \(\mathcal{H}\)-matrix node.
file hmatrix-fine-ntp-to-tp.cc
Verify the conversion of an \(\mathcal{H}\)-matrix from fine non-tensor product structure to tensor product structure.
file hmatrix-forward-substitution.cc
Verify forward substitution of a lower triangle \(\mathcal{H}\)-matrix. The block cluster tree partition structure is fine non-tensor product.
file hmatrix-forward-substitution-coarse-ntp.cc
Verify forward substitution of a lower triangle \(\mathcal{H}\)-matrix. The block cluster tree partition structure is coarse non-tensor product.
file hmatrix-forward-substitution-unit-diag.cc
Verify forward substitution of a unit lower triangle \(\mathcal{H}\)-matrix. The block cluster tree partition structure is fine non-tensor product.
file hmatrix-hmatrix-alpha-mmult-level-conserving-all-fine-ntp-member-function-call.cc
Verify the multiplication of two level-conserving \(\mathcal{H}\)-matrices with the result scaled by a factor, i.e. \(M = M + \alpha \cdot M_1 M_2\). Both operands and the result matrices have the fine non-tensor product partitions. This version uses the member function call of multiplication.
file hmatrix-hmatrix-alpha-mTmult-level-conserving-all-fine-ntp-member-function-call.cc
Verify the multiplication of two level-conserving \(\mathcal{H}\)-matrices with the second operand transposed and with the result scaled by a factor, i.e. \(M = M + \alpha \cdot M_1 M_2\). Both operands and the result matrices have the fine non-tensor product partitions. This version uses the member function call of multiplication.
file hmatrix-hmatrix-mmult-level-conserving-all-fine-ntp.cc
Verify the multiplication of two level-conserving \(\mathcal{H}\)-matrices. Both operands and the result matrices have the fine non-tensor product partitions.
file hmatrix-hmatrix-mmult-level-conserving-coarse-coarse-fine-ntp.cc
Verify the multiplication of two level-conserving \(\mathcal{H}\)-matrices. Both operands have the coarse non-tensor product partitions, while the result matrix has the fine non-tensor product partitions.
file hmatrix-hmatrix-mmult-level-conserving-coarse-fine-coarse-ntp.cc
Verify the multiplication of two level-conserving \(\mathcal{H}\)-matrices. The first operand and the result matrix have the coarse non-tensor product partitions, while the second operand has the fine non-tensor product partitions.
file hmatrix-hmatrix-mmult-level-conserving-fine-coarse-fine-ntp.cc
Verify the multiplication of two level-conserving \(\mathcal{H}\)-matrices. The first operand and the result matrix have the fine non-tensor product partitions, while the second operand has the coarse non-tensor product partitions.
file hmatrix-hmatrix-mmult-level-conserving-fine-fine-coarse-ntp.cc
Verify the multiplication of two level-conserving \(\mathcal{H}\)-matrices. Both operands have the fine non-tensor product partitions, while the result matrix has the coarse non-tensor product partitions.
file hmatrix-hmatrix-mTmult-level-conserving-all-fine-ntp.cc
Verify the multiplication of two level-conserving \(\mathcal{H}\)-matrices with the second operand transposed. Both operands and the result matrices have the fine non-tensor product partitions.
file hmatrix-hmatrix-mTmult-level-conserving-coarse-coarse-fine-ntp.cc
Verify the multiplication of two level-conserving \(\mathcal{H}\)-matrices with the second operand transposed. Both operands have the coarse non-tensor product partitions, while the result matrix has the fine non-tensor product partitions.
file hmatrix-hmatrix-mTmult-level-conserving-coarse-fine-coarse-ntp.cc
Verify the multiplication of two level-conserving \(\mathcal{H}\)-matrices with the second operand transposed. The first operand and the result matrix have the coarse non-tensor product partitions, while the second operand has the fine non-tensor product partitions.
file hmatrix-hmatrix-mTmult-level-conserving-fine-coarse-fine-ntp.cc
Verify the multiplication of two level-conserving \(\mathcal{H}\)-matrices with the second operand transposed. The first operand and the result matrix have the fine non-tensor product partitions, while the second operand has the coarse non-tensor product partitions.
file hmatrix-hmatrix-mTmult-level-conserving-fine-fine-coarse-ntp.cc
Verify the multiplication of two level-conserving \(\mathcal{H}\)-matrices with the second operand transposed. Both operands have the fine non-tensor product partitions, while the result matrix has the coarse non-tensor product partitions.
file hmatrix-rkmatrix-conversion.cc
Verify the conversion from an H-matrix to a rank-k matrix.
file hmatrix-solve-cholesky.cc
Verify Cholesky factorization of a positive definite and symmetric \(\mathcal{H}\)-matrix and solve this matrix using forward and backward substitution.
file hmatrix-solve-cholesky-in-situ.cc
Verify in situ Cholesky factorization of a positive definite and symmetric \(\mathcal{H}\)-matrix and solve this matrix using forward and backward substitution.
file hmatrix-solve-cholesky-in-situ-for-erichsen1996efficient-example2.cc
Verify in situ Cholesky factorization of a positive definite and symmetric \(\mathcal{H}\)-matrix and solve this matrix using forward and backward substitution. This \(\mathcal{H}\)-matrix is generated from a discretization of Example 2 in Erichsen1996Efficient paper.
file hmatrix-solve-lu.cc
Verify LU factorization of an \(\mathcal{H}\)-matrix and solve this matrix using forward and backward substitution.
file hmatrix-solve-lu-in-situ.cc
Verify LU factorization (in-situ) of an \(\mathcal{H}\)-matrix and solve this matrix using forward and backward substitution.
file hmatrix-transpose-forward-substitution.cc
Verify forward substitution of the transpose of an upper triangle \(\mathcal{H}\)-matrix. The block cluster tree partition structure is fine non-tensor product.
file hmatrix-transpose-forward-substitution-matrix-valued.cc
Verify matrix-valued forward substitution of the transpose of a upper triangular \(\mathcal{H}\)-matrix.
file hmatrix-truncate-to-fixed-rank.cc
Verify the rank truncation of an \(\mathcal{H}\)-matrix.
file hmatrix-truncate-to-fixed-rank-preserve-spd.cc
Verify the rank truncation of an \(\mathcal{H}\)-matrix, while preserving its symmetric positive definiteness (SPD) property.
file hp-matrix.cc
Test the \(H^p\) matrix.
file rkmatrix-agglomeration.cc
Verify the agglomeration of four rank-k submatrices into a larger rank-k matrix.
Classes
class BlockCluster< spacedim, Number >
Class for block cluster.
class BlockClusterTree< spacedim, Number >
Class for block cluster tree.
class BinaryTreeNode< T >
Class for binary tree node.
template<int dim, int spacedim, typename Number = double>
void map_dofs_to_average_cell_size (const DoFHandler< dim, spacedim > &dof_handler, std::vector< Number > &dof_average_cell_size)
template<typename DoFHandlerType , typename Number = double>
void map_dofs_to_max_cell_size (const DoFHandlerType &dof_handler, std::vector< Number > &dof_max_cell_size)
template<typename DoFHandlerType , typename Number = double>
void map_dofs_to_min_cell_size (const DoFHandlerType &dof_handler, std::vector< Number > &dof_min_cell_size)
template<int spacedim, typename Number >
std::ostream & operator<< (std::ostream &out, const Cluster< spacedim, Number > &cluster)
template<int spacedim, typename Number = double>
Number calc_cluster_distance (const Cluster< spacedim, Number > &cluster1, const Cluster< spacedim, Number > &cluster2, const std::vector< Point< spacedim, Number >> &all_support_points)
template<int spacedim, typename Number = double>
Number calc_cluster_distance (const Cluster< spacedim, Number > &cluster1, const Cluster< spacedim, Number > &cluster2, const std::vector< Point< spacedim, Number >> &all_support_points, const std::vector< Number > &cell_size_at_dofs)
template<int spacedim, typename Number >
bool operator== (const Cluster< spacedim, Number > &cluster1, const Cluster< spacedim, Number > &cluster2)
Detailed Description
Implementation of hierarchical matrix data structure and algebraic operations.
Function Documentation
calc_cluster_distance() [1/2]
template<int spacedim, typename Number = double> Number calc_cluster_distance (const Cluster< spacedim, Number > & cluster1, const Cluster< spacedim, Number > & cluster2, const std::vector< Point< spacedim, Number >> & all_support_points)
Calculate the minimum distance between two clusters. This calculation has no mesh size correction.
The calculation is based on measuring the distance between each pair of support points contained in the clusters, which prevents the distance calculation between two support sets.
Parameters
cluster1
cluster2
all_support_points A list of support point coordinates which are ordered by DoF indices.
Returns
References Cluster< spacedim, Number >::get_index_set().
calc_cluster_distance() [2/2]
template<int spacedim, typename Number = double> Number calc_cluster_distance (const Cluster< spacedim, Number > & cluster1, const Cluster< spacedim, Number > & cluster2, const std::vector< Point< spacedim, Number >> & all_support_points, const std::vector< Number > & cell_size_at_dofs)
Calculate the minimum distance between two clusters. This calculation has the mesh size correction.
The calculation is based on measuring the distance between each pair of support points contained in the clusters, which prevents the distance calculation between two support sets.
Parameters
cluster1
cluster2
all_support_points A list of support point coordinates which are ordered by DoF indices.
cell_size_at_dofs The list of estimated cell size values at DoF support points.
Returns
Calculate the uncorrected cluster distance.
Get the maximum diameter of the support sets for different DoFs, which is 2 times of the cell size associated with the corresponding DoF.
Ensure the positivity of the returned cluster distance.
References Cluster< spacedim, Number >::get_index_set().
map_dofs_to_average_cell_size()
template<int dim, int spacedim, typename Number = double> void map_dofs_to_average_cell_size (const DoFHandler< dim, spacedim > & dof_handler, std::vector< Number > & dof_average_cell_size)
Calculate the average cell sizes associated with those DoFs handled by the given DoF handler object.
The value doubled is used as an estimate for the diameter of the support set of each DoF.
Parameters
dof_average_cell_size The returned list of average cell sizes. The memory for this vector should be preallocated and initialized to zero before calling this function.
Create the vector which stores the number of cells that share a common DoF for each DoF.
Get the diameter of the current cell.
Get DoF indices local to this cell.
Referenced by LaplaceBEM::Erichsen1996Efficient::Example2::build_slp_only(), and main().
map_dofs_to_max_cell_size()
template<typename DoFHandlerType , typename Number = double> void map_dofs_to_max_cell_size (const DoFHandlerType & dof_handler, std::vector< Number > & dof_max_cell_size)
Calculate the maximum cell sizes associated with those DoFs handled by the given DoF handler object.
The value doubled is used as an estimate for the diameter of the support set of each DoF.
Parameters
dof_max_cell_size The returned list of maximum cell sizes. The memory for this vector should be preallocated and initialized to zero before calling this function.
Get the diameter of the current cell.
Get DoF indices local to this cell.
Referenced by main().
map_dofs_to_min_cell_size()
template<typename DoFHandlerType , typename Number = double> void map_dofs_to_min_cell_size (const DoFHandlerType & dof_handler, std::vector< Number > & dof_min_cell_size)
Calculate the minimum cell sizes associated with those DoFs handled by the given DoF handler object.
The value doubled is used as an estimate for the diameter of the support set of each DoF.
Parameters
dof_min_cell_size The returned list of average cell sizes. The memory for this vector should be preallocated and initialized to zero before calling this function.
Get the diameter of the current cell.
Get DoF indices local to this cell.
Referenced by main().
operator<<()
template<int spacedim, typename Number > std::ostream& operator<< (std::ostream & out, const Cluster< spacedim, Number > & cluster)
Print out the cluster data.
Parameters
out
cluster
Returns