laplace-bem: /home/jihuan/Projects/deal.ii/program/dealii-9.1.1/examples/laplace-bem/include/laplace_bem.h File Reference
laplace_bem.h File Reference
Sauter quadrature
Implementation of BEM involving kernel functions and singular numerical quadratures.
#include <deal.II/base/point.h>
#include <deal.II/base/subscriptor.h>
#include <deal.II/base/table.h>
#include <deal.II/base/table_indices.h>
#include <deal.II/dofs/dof_accessor.h>
#include <deal.II/dofs/dof_handler.h>
#include <deal.II/fe/fe.h>
#include <deal.II/fe/fe_base.h>
#include <deal.II/fe/fe_q.h>
#include <deal.II/fe/fe_values.h>
#include <deal.II/fe/mapping_q_generic.h>
#include <deal.II/lac/full_matrix.templates.h>
#include <deal.II/grid/tria.h>
#include <algorithm>
#include <array>
#include <cmath>
#include <vector>
#include "quadrature.templates.h"
Classes
class LaplaceBEM::BEMValues< dim, spacedim, RangeNumberType >
class LaplaceBEM::BEMValues< dim, spacedim, RangeNumberType >
struct LaplaceBEM::CellWisePerTaskData
struct LaplaceBEM::CellWiseScratchData
struct LaplaceBEM::PairCellWiseScratchData
struct LaplaceBEM::PairCellWisePerTaskData
class LaplaceBEM::LaplaceKernel::KernelFunction< dim, RangeNumberType >
class LaplaceBEM::LaplaceKernel::SingleLayerKernel< dim, RangeNumberType >
class LaplaceBEM::LaplaceKernel::DoubleLayerKernel< dim, RangeNumberType >
class LaplaceBEM::LaplaceKernel::AdjointDoubleLayerKernel< dim, RangeNumberType >
class LaplaceBEM::LaplaceKernel::HyperSingularKernel< dim, RangeNumberType >
class LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >
class LaplaceBEM::KernelPulledbackToSauterSpace< dim, spacedim, RangeNumberType >
Enumerations
enum CellNeighboringType {
SamePanel, CommonEdge, CommonVertex, Regular,
None
}
enum KernelType {
SingleLayer, DoubleLayer, AdjointDoubleLayer, HyperSingular,
NoneType
}
Functions
template<int dim, int spacedim, typename RangeNumberType = double>
void LaplaceBEM::bem_shape_values_same_panel (const FiniteElement< dim, spacedim > &kx_fe, const FiniteElement< dim, spacedim > &ky_fe, const QGauss< 4 > &sauter_quad_rule, Table< 3, RangeNumberType > &kx_shape_value_table, Table< 3, RangeNumberType > &ky_shape_value_table)
template<int dim, int spacedim, typename RangeNumberType = double>
void LaplaceBEM::bem_shape_values_common_edge (const FiniteElement< dim, spacedim > &kx_fe, const FiniteElement< dim, spacedim > &ky_fe, const QGauss< 4 > &sauter_quad_rule, Table< 3, RangeNumberType > &kx_shape_value_table, Table< 3, RangeNumberType > &ky_shape_value_table)
template<int dim, int spacedim, typename RangeNumberType = double>
void LaplaceBEM::bem_shape_values_common_vertex (const FiniteElement< dim, spacedim > &kx_fe, const FiniteElement< dim, spacedim > &ky_fe, const QGauss< 4 > &sauter_quad_rule, Table< 3, RangeNumberType > &kx_shape_value_table, Table< 3, RangeNumberType > &ky_shape_value_table)
template<int dim, int spacedim, typename RangeNumberType = double>
void LaplaceBEM::bem_shape_values_regular (const FiniteElement< dim, spacedim > &kx_fe, const FiniteElement< dim, spacedim > &ky_fe, const QGauss< 4 > &sauter_quad_rule, Table< 3, RangeNumberType > &kx_shape_value_table, Table< 3, RangeNumberType > &ky_shape_value_table)
template<int dim, int spacedim, typename RangeNumberType = double>
void LaplaceBEM::bem_shape_grad_matrices_same_panel (const FiniteElement< dim, spacedim > &kx_fe, const FiniteElement< dim, spacedim > &ky_fe, const QGauss< 4 > &sauter_quad_rule, Table< 2, FullMatrix< RangeNumberType >> &kx_shape_grad_matrix_table, Table< 2, FullMatrix< RangeNumberType >> &ky_shape_grad_matrix_table)
template<int dim, int spacedim, typename RangeNumberType = double>
void LaplaceBEM::bem_shape_grad_matrices_common_edge (const FiniteElement< dim, spacedim > &kx_fe, const FiniteElement< dim, spacedim > &ky_fe, const QGauss< 4 > &sauter_quad_rule, Table< 2, FullMatrix< RangeNumberType >> &kx_shape_grad_matrix_table, Table< 2, FullMatrix< RangeNumberType >> &ky_shape_grad_matrix_table)
template<int dim, int spacedim, typename RangeNumberType = double>
void LaplaceBEM::bem_shape_grad_matrices_common_vertex (const FiniteElement< dim, spacedim > &kx_fe, const FiniteElement< dim, spacedim > &ky_fe, const QGauss< 4 > &sauter_quad_rule, Table< 2, FullMatrix< RangeNumberType >> &kx_shape_grad_matrix_table, Table< 2, FullMatrix< RangeNumberType >> &ky_shape_grad_matrix_table)
template<int dim, int spacedim, typename RangeNumberType = double>
void LaplaceBEM::bem_shape_grad_matrices_regular (const FiniteElement< dim, spacedim > &kx_fe, const FiniteElement< dim, spacedim > &ky_fe, const QGauss< 4 > &sauter_quad_rule, Table< 2, FullMatrix< RangeNumberType >> &kx_shape_grad_matrix_table, Table< 2, FullMatrix< RangeNumberType >> &ky_shape_grad_matrix_table)
template<int dim, int spacedim>
std::vector< types::global_dof_index > LaplaceBEM::get_conflict_indices (const typename DoFHandler< dim, spacedim >::active_cell_iterator &cell)
template<int dim, int spacedim>
std::array< types::global_vertex_index, GeometryInfo< dim >::vertices_per_cell > LaplaceBEM::get_vertex_indices (const typename Triangulation< dim, spacedim >::cell_iterator &cell)
template<int dim, int spacedim>
std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > LaplaceBEM::get_vertex_dof_indices (const typename DoFHandler< dim, spacedim >::cell_iterator &cell)
template<int dim>
CellNeighboringType LaplaceBEM::detect_cell_neighboring_type (const std::array< types::global_vertex_index, GeometryInfo< dim >::vertices_per_cell > &first_cell_vertex_indices, const std::array< types::global_vertex_index, GeometryInfo< dim >::vertices_per_cell > &second_cell_vertex_indices, std::vector< types::global_vertex_index > &vertex_index_intersection)
template<int dim>
CellNeighboringType LaplaceBEM::detect_cell_neighboring_type (const std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > &first_cell_vertex_dof_indices, const std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > &second_cell_vertex_dof_indices, std::vector< types::global_dof_index > &vertex_dof_index_intersection)
template<int dim, int spacedim, typename Number = double>
Number LaplaceBEM::cell_distance (const typename Triangulation< dim, spacedim >::cell_iterator first_cell, const typename Triangulation< dim, spacedim >::cell_iterator second_cell)
template<int dim, int spacedim>
FullMatrix< double > LaplaceBEM::shape_grad_matrix (const FiniteElement< dim, spacedim > &fe, const std::vector< unsigned int > &dof_permutation, const Point< dim > &p)
template<int dim, int spacedim>
FullMatrix< double > LaplaceBEM::shape_grad_matrix_in_hierarchical_order (const FiniteElement< dim, spacedim > &fe, const Point< dim > &p)
template<int dim, int spacedim>
FullMatrix< double > LaplaceBEM::shape_grad_matrix_in_tensor_product_order (const FiniteElement< dim, spacedim > &fe, const Point< dim > &p)
template<int dim, int spacedim>
Vector< double > LaplaceBEM::shape_values (const FiniteElement< dim, spacedim > &fe, const std::vector< unsigned int > &dof_permutation, const Point< dim > &p)
template<int dim, int spacedim>
Vector< double > LaplaceBEM::shape_values_in_hierarchical_order (const FiniteElement< dim, spacedim > &fe, const Point< dim > &p)
template<int dim, int spacedim>
Vector< double > LaplaceBEM::shape_values_in_tensor_product_order (const FiniteElement< dim, spacedim > &fe, const Point< dim > &p)
FullMatrix< double > LaplaceBEM::collect_two_components_from_point3 (const std::vector< Point< 3 >> &points, const unsigned int first_component, const unsigned int second_component)
template<int dim, int spacedim>
std::vector< Point< spacedim > > LaplaceBEM::support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const FiniteElement< dim, spacedim > &fe, const MappingQGeneric< dim, spacedim > &mapping, const std::vector< unsigned int > &dof_permutation)
template<int dim, int spacedim>
std::vector< Point< spacedim > > LaplaceBEM::hierarchical_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const FiniteElement< dim, spacedim > &fe, const MappingQGeneric< dim, spacedim > &mapping)
template<int dim, int spacedim>
void LaplaceBEM::hierarchical_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const FiniteElement< dim, spacedim > &fe, const MappingQGeneric< dim, spacedim > &mapping, std::vector< Point< spacedim >> &real_support_points)
template<int dim, int spacedim>
std::vector< Point< spacedim > > LaplaceBEM::tensor_product_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator &cell, const FiniteElement< dim, spacedim > &fe, const MappingQGeneric< dim, spacedim > &mapping)
template<int dim, int spacedim>
double LaplaceBEM::surface_jacobian_det (const FiniteElement< dim, spacedim > &fe, const std::vector< Point< spacedim >> &support_points_in_real_cell, const Point< dim > &p)
template<int spacedim>
double LaplaceBEM::surface_jacobian_det (const unsigned int k3_index, const unsigned int quad_no, const Table< 2, FullMatrix< double >> &shape_grad_matrix_table, const std::vector< Point< spacedim >> &support_points_in_real_cell)
template<int dim, int spacedim>
double LaplaceBEM::surface_jacobian_det_and_normal_vector (const FiniteElement< dim, spacedim > &fe, const std::vector< Point< spacedim >> &support_points_in_real_cell, const Point< dim > &p, Tensor< 1, spacedim > &normal_vector)
template<int spacedim>
double LaplaceBEM::surface_jacobian_det_and_normal_vector (const unsigned int k3_index, const unsigned int quad_no, const Table< 2, FullMatrix< double >> &shape_grad_matrix_table, const std::vector< Point< spacedim >> &support_points_in_real_cell, Tensor< 1, spacedim > &normal_vector)
template<int dim, int spacedim>
Point< spacedim > LaplaceBEM::transform_unit_to_permuted_real_cell (const FiniteElement< dim, spacedim > &fe, const std::vector< Point< spacedim >> &support_points_in_real_cell, const Point< dim > &area_coords)
template<int spacedim>
Point< spacedim > LaplaceBEM::transform_unit_to_permuted_real_cell (const unsigned int k3_index, const unsigned int quad_no, const Table< 3, double > &shape_value_table, const std::vector< Point< spacedim >> &support_points_in_real_cell)
template<int dim, int spacedim>
std::vector< unsigned int > LaplaceBEM::generate_forward_dof_permutation (const FiniteElement< dim, spacedim > &fe, unsigned int starting_corner)
template<int dim, int spacedim>
void LaplaceBEM::generate_forward_dof_permutation (const FiniteElement< dim, spacedim > &fe, unsigned int starting_corner, std::vector< unsigned int > &dof_permutation)
template<int dim, int spacedim>
std::vector< unsigned int > LaplaceBEM::generate_backward_dof_permutation (const FiniteElement< dim, spacedim > &fe, unsigned int starting_corner)
template<int dim, int spacedim>
void LaplaceBEM::generate_backward_dof_permutation (const FiniteElement< dim, spacedim > &fe, unsigned int starting_corner, std::vector< unsigned int > &dof_permutation)
template<typename T >
std::vector< T > LaplaceBEM::permute_vector (const std::vector< T > &input_vector, const std::vector< unsigned int > &permutation_indices)
template<typename T >
void LaplaceBEM::permute_vector (const std::vector< T > &input_vector, const std::vector< unsigned int > &permutation_indices, std::vector< T > &permuted_vector)
template<int dim, int spacedim, typename RangeNumberType = double>
RangeNumberType LaplaceBEM::ApplyQuadrature (const Quadrature< dim *2 > &quad_rule, const KernelPulledbackToSauterSpace< dim, spacedim, RangeNumberType > &f, unsigned int component=0)
template<int dim, int spacedim, typename RangeNumberType = double>
RangeNumberType LaplaceBEM::ApplyQuadratureUsingBEMValues (const Quadrature< dim *2 > &quad_rule, const KernelPulledbackToSauterSpace< dim, spacedim, RangeNumberType > &f, unsigned int component=0)
template<int dim, int spacedim>
std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > LaplaceBEM::get_vertex_dof_indices_swapped (const FiniteElement< dim, spacedim > &fe, const std::vector< types::global_dof_index > &dof_indices)
template<int dim, int spacedim>
void LaplaceBEM::get_vertex_dof_indices_swapped (const FiniteElement< dim, spacedim > &fe, const std::vector< types::global_dof_index > &dof_indices, std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > &vertex_dof_indices)
template<int vertices_per_cell>
unsigned int LaplaceBEM::get_start_vertex_dof_index (const std::vector< types::global_dof_index > &vertex_dof_index_intersection, const std::array< types::global_dof_index, vertices_per_cell > &local_vertex_dof_indices_swapped)
template<int dim, int spacedim, typename RangeNumberType = double>
FullMatrix< RangeNumberType > LaplaceBEM::SauterQuadRule (const LaplaceKernel::KernelFunction< spacedim, RangeNumberType > &kernel_function, const typename DoFHandler< dim, spacedim >::cell_iterator &kx_cell_iter, const typename DoFHandler< dim, spacedim >::cell_iterator &ky_cell_iter, const MappingQGeneric< dim, spacedim > &kx_mapping=MappingQGeneric< dim, spacedim >(1), const MappingQGeneric< dim, spacedim > &ky_mapping=MappingQGeneric< dim, spacedim >(1))
template<int dim, int spacedim, typename RangeNumberType = double>
FullMatrix< RangeNumberType > LaplaceBEM::SauterQuadRule (const LaplaceKernel::KernelFunction< spacedim, RangeNumberType > &kernel_function, const BEMValues< dim, spacedim > &bem_values, const typename DoFHandler< dim, spacedim >::cell_iterator &kx_cell_iter, const typename DoFHandler< dim, spacedim >::cell_iterator &ky_cell_iter, const MappingQGeneric< dim, spacedim > &kx_mapping=MappingQGeneric< dim, spacedim >(1), const MappingQGeneric< dim, spacedim > &ky_mapping=MappingQGeneric< dim, spacedim >(1))
template<int dim>
void LaplaceBEM::sauter_same_panel_parametric_coords_to_unit_cells (const Point< dim *2 > &parametric_coords, const unsigned int k3_index, Point< dim > &kx_unit_cell_coords, Point< dim > &ky_unit_cell_coords)
template<int dim>
void LaplaceBEM::sauter_common_edge_parametric_coords_to_unit_cells (const Point< dim *2 > &parametric_coords, const unsigned int k3_index, Point< dim > &kx_unit_cell_coords, Point< dim > &ky_unit_cell_coords)
template<int dim>
void LaplaceBEM::sauter_common_vertex_parametric_coords_to_unit_cells (const Point< dim *2 > &parametric_coords, const unsigned int k3_index, Point< dim > &kx_unit_cell_coords, Point< dim > &ky_unit_cell_coords)
template<int dim>
void LaplaceBEM::sauter_regular_parametric_coords_to_unit_cells (const Point< dim *2 > &parametric_coords, Point< dim > &kx_unit_cell_coords, Point< dim > &ky_unit_cell_coords)
template<int dim, int spacedim, typename RangeNumberType = double>
void LaplaceBEM::SauterQuadRule (FullMatrix< RangeNumberType > &system_matrix, const LaplaceKernel::KernelFunction< spacedim, RangeNumberType > &kernel_function, const typename DoFHandler< dim, spacedim >::cell_iterator &kx_cell_iter, const typename DoFHandler< dim, spacedim >::cell_iterator &ky_cell_iter, const MappingQGeneric< dim, spacedim > &kx_mapping=MappingQGeneric< dim, spacedim >(1), const MappingQGeneric< dim, spacedim > &ky_mapping=MappingQGeneric< dim, spacedim >(1))
template<int dim, int spacedim, typename RangeNumberType = double>
void LaplaceBEM::SauterQuadRule (FullMatrix< RangeNumberType > &system_matrix, const LaplaceKernel::KernelFunction< spacedim, RangeNumberType > &kernel_function, const BEMValues< dim, spacedim > &bem_values, const typename DoFHandler< dim, spacedim >::cell_iterator &kx_cell_iter, const typename DoFHandler< dim, spacedim >::cell_iterator &ky_cell_iter, const MappingQGeneric< dim, spacedim > &kx_mapping=MappingQGeneric< dim, spacedim >(1), const MappingQGeneric< dim, spacedim > &ky_mapping=MappingQGeneric< dim, spacedim >(1))
Detailed Description
Implementation of BEM involving kernel functions and singular numerical quadratures.
Date
2020-11-02
Author
Jihuan Tian
Function Documentation
bem_shape_grad_matrices_common_edge()
template<int dim, int spacedim, typename RangeNumberType = double> void LaplaceBEM::bem_shape_grad_matrices_common_edge (const FiniteElement< dim, spacedim > & kx_fe, const FiniteElement< dim, spacedim > & ky_fe, const QGauss< 4 > & sauter_quad_rule, Table< 2, FullMatrix< RangeNumberType >> & kx_shape_grad_matrix_table, Table< 2, FullMatrix< RangeNumberType >> & ky_shape_grad_matrix_table)
Calculate the table storing shape function gradient matrices at Sauter quadrature points for the common edge case. N.B. The shape functions are in the tensor product order and each row of the gradient matrix corresponds to a shape function.
Parameters
kx_fe finite element for $K_x$
ky_fe finite element for $K_y$
sauter_quad_rule
kx_shape_grad_matrix_table the 1st dimension is the index for $k_3$ terms; the 2nd dimension is the quadrature point number.
ky_shape_grad_matrix_table the 1st dimension is the index for $k_3$ terms; the 2nd dimension is the quadrature point number.
References LaplaceBEM::bem_shape_grad_matrices_common_edge(), and LaplaceBEM::sauter_common_edge_parametric_coords_to_unit_cells().
Referenced by LaplaceBEM::bem_shape_grad_matrices_common_edge(), and LaplaceBEM::BEMValues< dim, spacedim, RangeNumberType >::BEMValues().
bem_shape_grad_matrices_common_vertex()
template<int dim, int spacedim, typename RangeNumberType = double> void LaplaceBEM::bem_shape_grad_matrices_common_vertex (const FiniteElement< dim, spacedim > & kx_fe, const FiniteElement< dim, spacedim > & ky_fe, const QGauss< 4 > & sauter_quad_rule, Table< 2, FullMatrix< RangeNumberType >> & kx_shape_grad_matrix_table, Table< 2, FullMatrix< RangeNumberType >> & ky_shape_grad_matrix_table)
Calculate the table storing shape function gradient matrices at Sauter quadrature points for the common vertex case. N.B. The shape functions are in the tensor product order and each row of the gradient matrix corresponds to a shape function.
Parameters
kx_fe finite element for $K_x$
ky_fe finite element for $K_y$
sauter_quad_rule
kx_shape_grad_matrix_table the 1st dimension is the index for $k_3$ terms; the 2nd dimension is the quadrature point number.
ky_shape_grad_matrix_table the 1st dimension is the index for $k_3$ terms; the 2nd dimension is the quadrature point number.
References LaplaceBEM::bem_shape_grad_matrices_common_vertex(), and LaplaceBEM::sauter_common_vertex_parametric_coords_to_unit_cells().
Referenced by LaplaceBEM::bem_shape_grad_matrices_common_vertex(), and LaplaceBEM::BEMValues< dim, spacedim, RangeNumberType >::BEMValues().
bem_shape_grad_matrices_regular()
template<int dim, int spacedim, typename RangeNumberType = double> void LaplaceBEM::bem_shape_grad_matrices_regular (const FiniteElement< dim, spacedim > & kx_fe, const FiniteElement< dim, spacedim > & ky_fe, const QGauss< 4 > & sauter_quad_rule, Table< 2, FullMatrix< RangeNumberType >> & kx_shape_grad_matrix_table, Table< 2, FullMatrix< RangeNumberType >> & ky_shape_grad_matrix_table)
Calculate the table storing shape function gradient matrices at Sauter quadrature points for the regular case. N.B. The shape functions are in the tensor product order and each row of the gradient matrix corresponds to a shape function.
Parameters
kx_fe finite element for $K_x$
ky_fe finite element for $K_y$
sauter_quad_rule
kx_shape_grad_matrix_table the 1st dimension is the quadrature point number.
ky_shape_grad_matrix_table the 1st dimension is the quadrature point number.
References LaplaceBEM::bem_shape_grad_matrices_regular(), and LaplaceBEM::sauter_regular_parametric_coords_to_unit_cells().
Referenced by LaplaceBEM::bem_shape_grad_matrices_regular(), and LaplaceBEM::BEMValues< dim, spacedim, RangeNumberType >::BEMValues().
bem_shape_grad_matrices_same_panel()
template<int dim, int spacedim, typename RangeNumberType = double> void LaplaceBEM::bem_shape_grad_matrices_same_panel (const FiniteElement< dim, spacedim > & kx_fe, const FiniteElement< dim, spacedim > & ky_fe, const QGauss< 4 > & sauter_quad_rule, Table< 2, FullMatrix< RangeNumberType >> & kx_shape_grad_matrix_table, Table< 2, FullMatrix< RangeNumberType >> & ky_shape_grad_matrix_table)
Calculate the table storing shape function gradient matrices at Sauter quadrature points for the same panel case. N.B. The shape functions are in the tensor product order and each row of the gradient matrix corresponds to a shape function.
Parameters
kx_fe finite element for $K_x$
ky_fe finite element for $K_y$
sauter_quad_rule
kx_shape_grad_matrix_table the 1st dimension is the index for $k_3$ terms; the 2nd dimension is the quadrature point number.
ky_shape_grad_matrix_table the 1st dimension is the index for $k_3$ terms; the 2nd dimension is the quadrature point number.
References LaplaceBEM::bem_shape_grad_matrices_same_panel(), and LaplaceBEM::sauter_same_panel_parametric_coords_to_unit_cells().
Referenced by LaplaceBEM::bem_shape_grad_matrices_same_panel(), and LaplaceBEM::BEMValues< dim, spacedim, RangeNumberType >::BEMValues().
bem_shape_values_common_edge()
template<int dim, int spacedim, typename RangeNumberType = double> void LaplaceBEM::bem_shape_values_common_edge (const FiniteElement< dim, spacedim > & kx_fe, const FiniteElement< dim, spacedim > & ky_fe, const QGauss< 4 > & sauter_quad_rule, Table< 3, RangeNumberType > & kx_shape_value_table, Table< 3, RangeNumberType > & ky_shape_value_table)
Calculate the table storing shape function values at Sauter quadrature points for the common edge case.
Parameters
kx_fe finite element for $K_x$
ky_fe finite element for $K_y$
sauter_quad_rule
kx_shape_value_table the 1st dimension is the shape function hierarchical numbering; the 2nd dimension is the index for $k_3$ terms; the 3rd dimension is the quadrature point number.
ky_shape_value_table the 1st dimension is the shape function hierarchical numbering; the 2nd dimension is the index for $k_3$ terms; the 3rd dimension is the quadrature point number.
References LaplaceBEM::bem_shape_values_common_edge(), and LaplaceBEM::sauter_common_edge_parametric_coords_to_unit_cells().
Referenced by LaplaceBEM::bem_shape_values_common_edge(), and LaplaceBEM::BEMValues< dim, spacedim, RangeNumberType >::BEMValues().
bem_shape_values_common_vertex()
template<int dim, int spacedim, typename RangeNumberType = double> void LaplaceBEM::bem_shape_values_common_vertex (const FiniteElement< dim, spacedim > & kx_fe, const FiniteElement< dim, spacedim > & ky_fe, const QGauss< 4 > & sauter_quad_rule, Table< 3, RangeNumberType > & kx_shape_value_table, Table< 3, RangeNumberType > & ky_shape_value_table)
Calculate the table storing shape function values at Sauter quadrature points for the common vertex case.
Parameters
kx_fe finite element for $K_x$
ky_fe finite element for $K_y$
sauter_quad_rule
kx_shape_value_table the 1st dimension is the shape function hierarchical numbering; the 2nd dimension is the index for $k_3$ terms; the 3rd dimension is the quadrature point number.
ky_shape_value_table the 1st dimension is the shape function hierarchical numbering; the 2nd dimension is the index for $k_3$ terms; the 3rd dimension is the quadrature point number.
References LaplaceBEM::bem_shape_values_common_vertex(), and LaplaceBEM::sauter_common_vertex_parametric_coords_to_unit_cells().
Referenced by LaplaceBEM::bem_shape_values_common_vertex(), and LaplaceBEM::BEMValues< dim, spacedim, RangeNumberType >::BEMValues().
bem_shape_values_regular()
template<int dim, int spacedim, typename RangeNumberType = double> void LaplaceBEM::bem_shape_values_regular (const FiniteElement< dim, spacedim > & kx_fe, const FiniteElement< dim, spacedim > & ky_fe, const QGauss< 4 > & sauter_quad_rule, Table< 3, RangeNumberType > & kx_shape_value_table, Table< 3, RangeNumberType > & ky_shape_value_table)
Calculate the table storing shape function values at Sauter quadrature points for the regular case.
Parameters
kx_fe finite element for $K_x$
ky_fe finite element for $K_y$
sauter_quad_rule
kx_shape_value_table the 1st dimension is the shape function hierarchical numbering; the 2nd dimension is the index for $k_3$ terms; the 3rd dimension is the quadrature point number.
ky_shape_value_table the 1st dimension is the shape function hierarchical numbering; the 2nd dimension is the index for $k_3$ terms; the 3rd dimension is the quadrature point number.
References LaplaceBEM::bem_shape_values_regular(), and LaplaceBEM::sauter_regular_parametric_coords_to_unit_cells().
Referenced by LaplaceBEM::bem_shape_values_regular(), and LaplaceBEM::BEMValues< dim, spacedim, RangeNumberType >::BEMValues().
bem_shape_values_same_panel()
template<int dim, int spacedim, typename RangeNumberType = double> void LaplaceBEM::bem_shape_values_same_panel (const FiniteElement< dim, spacedim > & kx_fe, const FiniteElement< dim, spacedim > & ky_fe, const QGauss< 4 > & sauter_quad_rule, Table< 3, RangeNumberType > & kx_shape_value_table, Table< 3, RangeNumberType > & ky_shape_value_table)
Calculate the table storing shape function values at Sauter quadrature points for the same panel case.
Parameters
kx_fe finite element for $K_x$
ky_fe finite element for $K_y$
sauter_quad_rule
kx_shape_value_table the 1st dimension is the shape function hierarchical numbering; the 2nd dimension is the index for $k_3$ terms; the 3rd dimension is the quadrature point number.
ky_shape_value_table the 1st dimension is the shape function hierarchical numbering; the 2nd dimension is the index for $k_3$ terms; the 3rd dimension is the quadrature point number.
References LaplaceBEM::bem_shape_values_same_panel(), and LaplaceBEM::sauter_same_panel_parametric_coords_to_unit_cells().
Referenced by LaplaceBEM::bem_shape_values_same_panel(), and LaplaceBEM::BEMValues< dim, spacedim, RangeNumberType >::BEMValues().
generate_backward_dof_permutation() [1/2]
template<int dim, int spacedim> std::vector<unsigned int> LaplaceBEM::generate_backward_dof_permutation (const FiniteElement< dim, spacedim > & fe, unsigned int starting_corner)
Generate the permutation of polynomial space inverse numbering by starting from the specified corner in the backward direction. The index for starting_corner starts from zero.
References LaplaceBEM::generate_backward_dof_permutation().
Referenced by LaplaceBEM::generate_backward_dof_permutation().
generate_backward_dof_permutation() [2/2]
template<int dim, int spacedim> void LaplaceBEM::generate_backward_dof_permutation (const FiniteElement< dim, spacedim > & fe, unsigned int starting_corner, std::vector< unsigned int > & dof_permutation)
Generate the permutation of polynomial space inverse numbering by starting from the specified corner in the backward direction. The index for starting_corner starts from zero. This overloaded version has the returned vector as its argument.
References LaplaceBEM::generate_backward_dof_permutation().
generate_forward_dof_permutation() [1/2]
template<int dim, int spacedim> std::vector<unsigned int> LaplaceBEM::generate_forward_dof_permutation (const FiniteElement< dim, spacedim > & fe, unsigned int starting_corner)
Generate the permutation of polynomial space inverse numbering by starting from the specified corner in the forward direction.
References LaplaceBEM::generate_forward_dof_permutation().
Referenced by LaplaceBEM::generate_forward_dof_permutation().
generate_forward_dof_permutation() [2/2]
template<int dim, int spacedim> void LaplaceBEM::generate_forward_dof_permutation (const FiniteElement< dim, spacedim > & fe, unsigned int starting_corner, std::vector< unsigned int > & dof_permutation)
Generate the permutation of polynomial space inverse numbering by starting from the specified corner in the forward direction. This overloaded version has the returned vector as its argument.
References LaplaceBEM::generate_forward_dof_permutation().
get_start_vertex_dof_index()
template<int vertices_per_cell> unsigned int LaplaceBEM::get_start_vertex_dof_index (const std::vector< types::global_dof_index > & vertex_dof_index_intersection, const std::array< types::global_dof_index, vertices_per_cell > & local_vertex_dof_indices_swapped)
Get the starting vertex DoF index.
References LaplaceBEM::get_start_vertex_dof_index().
Referenced by LaplaceBEM::get_start_vertex_dof_index().
get_vertex_dof_indices_swapped() [1/2]
template<int dim, int spacedim> std::array<types::global_dof_index, GeometryInfo<dim>::vertices_per_cell> LaplaceBEM::get_vertex_dof_indices_swapped (const FiniteElement< dim, spacedim > & fe, const std::vector< types::global_dof_index > & dof_indices)
Get the DoF vertex indices from a list of DoF indices which have been arranged in forward or backward tensor product ordering. N.B. There are GeometryInfo<dim>::vertices_per_cell vertices in the returned array, among which the last two DoF vertex indices have been swapped so that the vertex DoFs are arranged in clockwise or counter clockwise order instead of the zigzag order.
References LaplaceBEM::get_vertex_dof_indices_swapped().
Referenced by LaplaceBEM::get_vertex_dof_indices_swapped().
get_vertex_dof_indices_swapped() [2/2]
template<int dim, int spacedim> void LaplaceBEM::get_vertex_dof_indices_swapped (const FiniteElement< dim, spacedim > & fe, const std::vector< types::global_dof_index > & dof_indices, std::array< types::global_dof_index, GeometryInfo< dim >::vertices_per_cell > & vertex_dof_indices)
Get the DoF vertex indices from a list of DoF indices which have been arranged in forward or backward tensor product ordering. N.B. There are GeometryInfo<dim>::vertices_per_cell vertices in the returned array, among which the last two DoF vertex indices have been swapped so that the vertex DoFs are arranged in clockwise or counter clockwise order instead of the zigzag order.
References LaplaceBEM::get_vertex_dof_indices_swapped().
hierarchical_support_points_in_real_cell() [1/2]
template<int dim, int spacedim> std::vector<Point<spacedim> > LaplaceBEM::hierarchical_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator & cell, const FiniteElement< dim, spacedim > & fe, const MappingQGeneric< dim, spacedim > & mapping)
Calculate support points in real cell in the default hierarchical ordering.
References LaplaceBEM::hierarchical_support_points_in_real_cell().
Referenced by LaplaceBEM::Erichsen1996Efficient::Example2::assemble_on_one_pair_of_cells(), LaplaceBEM::hierarchical_support_points_in_real_cell(), and LaplaceBEM::SauterQuadRule().
hierarchical_support_points_in_real_cell() [2/2]
template<int dim, int spacedim> void LaplaceBEM::hierarchical_support_points_in_real_cell (const typename Triangulation< dim, spacedim >::cell_iterator & cell, const FiniteElement< dim, spacedim > & fe, const MappingQGeneric< dim, spacedim > & mapping, std::vector< Point< spacedim >> & real_support_points)
Calculate support points in real cell in the default hierarchical ordering. The memory for storing these support points is pre-allocated.
References LaplaceBEM::hierarchical_support_points_in_real_cell().
permute_vector()
template<typename T > void LaplaceBEM::permute_vector (const std::vector< T > & input_vector, const std::vector< unsigned int > & permutation_indices, std::vector< T > & permuted_vector)
Permute a vector according to the specified permutation indices. The memory for the output vector should be pre-allocated.
Parameters
input_vector
permutation_indices
permuted_vector
sauter_common_edge_parametric_coords_to_unit_cells()
template<int dim> void LaplaceBEM::sauter_common_edge_parametric_coords_to_unit_cells (const Point< dim *2 > & parametric_coords, const unsigned int k3_index, Point< dim > & kx_unit_cell_coords, Point< dim > & ky_unit_cell_coords)
Transform parametric coordinates in Sauter's quadrature rule for the common edge case to unit cell coordinates for $K_x$ and $K_y$ respectively.
Parameters
parametric_coords
k3_index
kx_unit_cell_coords
ky_unit_cell_coords
References LaplaceBEM::sauter_common_edge_parametric_coords_to_unit_cells().
Referenced by LaplaceBEM::bem_shape_grad_matrices_common_edge(), LaplaceBEM::bem_shape_values_common_edge(), and LaplaceBEM::sauter_common_edge_parametric_coords_to_unit_cells().
sauter_common_vertex_parametric_coords_to_unit_cells()
template<int dim> void LaplaceBEM::sauter_common_vertex_parametric_coords_to_unit_cells (const Point< dim *2 > & parametric_coords, const unsigned int k3_index, Point< dim > & kx_unit_cell_coords, Point< dim > & ky_unit_cell_coords)
Transform parametric coordinates in Sauter's quadrature rule for the common vertex case to unit cell coordinates for $K_x$ and $K_y$ respectively.
Parameters
parametric_coords
k3_index
kx_unit_cell_coords
ky_unit_cell_coords
References LaplaceBEM::sauter_common_vertex_parametric_coords_to_unit_cells().
Referenced by LaplaceBEM::bem_shape_grad_matrices_common_vertex(), LaplaceBEM::bem_shape_values_common_vertex(), and LaplaceBEM::sauter_common_vertex_parametric_coords_to_unit_cells().
sauter_regular_parametric_coords_to_unit_cells()
template<int dim> void LaplaceBEM::sauter_regular_parametric_coords_to_unit_cells (const Point< dim *2 > & parametric_coords, Point< dim > & kx_unit_cell_coords, Point< dim > & ky_unit_cell_coords)
Transform parametric coordinates in Sauter's quadrature rule for the regular case to unit cell coordinates for $K_x$ and $K_y$ respectively.
Parameters
parametric_coords
k3_index
kx_unit_cell_coords
ky_unit_cell_coords
References LaplaceBEM::sauter_regular_parametric_coords_to_unit_cells().
Referenced by LaplaceBEM::bem_shape_grad_matrices_regular(), LaplaceBEM::bem_shape_values_regular(), and LaplaceBEM::sauter_regular_parametric_coords_to_unit_cells().
sauter_same_panel_parametric_coords_to_unit_cells()
template<int dim> void LaplaceBEM::sauter_same_panel_parametric_coords_to_unit_cells (const Point< dim *2 > & parametric_coords, const unsigned int k3_index, Point< dim > & kx_unit_cell_coords, Point< dim > & ky_unit_cell_coords)
Transform parametric coordinates in Sauter's quadrature rule for the same panel case to unit cell coordinates for $K_x$ and $K_y$ respectively.
Parameters
parametric_coords
k3_index
kx_unit_cell_coords
ky_unit_cell_coords
References LaplaceBEM::sauter_same_panel_parametric_coords_to_unit_cells().
Referenced by LaplaceBEM::bem_shape_grad_matrices_same_panel(), LaplaceBEM::bem_shape_values_same_panel(), and LaplaceBEM::sauter_same_panel_parametric_coords_to_unit_cells().
SauterQuadRule() [1/3]
template<int dim, int spacedim, typename RangeNumberType = double> FullMatrix<RangeNumberType> LaplaceBEM::SauterQuadRule (const LaplaceKernel::KernelFunction< spacedim, RangeNumberType > & kernel_function, const typename DoFHandler< dim, spacedim >::cell_iterator & kx_cell_iter, const typename DoFHandler< dim, spacedim >::cell_iterator & ky_cell_iter, const MappingQGeneric< dim, spacedim > & kx_mapping = MappingQGeneric<dim, spacedim>(1), const MappingQGeneric< dim, spacedim > & ky_mapping = MappingQGeneric<dim, spacedim>(1))
This function implements Sauter's quadrature rule on quadrangular mesh. It handles various cases including same panel, common edge, common vertex and regular cell neighboring types.
Parameters
kernel_function Laplace kernel function.
kx_cell_iter Iterator pointing to $K_x$.
kx_cell_iter Iterator pointing to $K_y$.
kx_mapping Mapping used for $K_x$. Because a mesher usually generates 1st order grid, if there is no additional manifold specification, the mapping should be 1st order.
kx_mapping Mapping used for $K_y$. Because a mesher usually generates 1st order grid, if there is no additional manifold specification, the mapping should be 1st order.
References LaplaceBEM::hierarchical_support_points_in_real_cell(), and LaplaceBEM::SauterQuadRule().
Referenced by LaplaceBEM::SauterQuadRule().
SauterQuadRule() [2/3]
template<int dim, int spacedim, typename RangeNumberType = double> void LaplaceBEM::SauterQuadRule (FullMatrix< RangeNumberType > & system_matrix, const LaplaceKernel::KernelFunction< spacedim, RangeNumberType > & kernel_function, const typename DoFHandler< dim, spacedim >::cell_iterator & kx_cell_iter, const typename DoFHandler< dim, spacedim >::cell_iterator & ky_cell_iter, const MappingQGeneric< dim, spacedim > & kx_mapping = MappingQGeneric<dim, spacedim>(1), const MappingQGeneric< dim, spacedim > & ky_mapping = MappingQGeneric<dim, spacedim>(1))
This function implements Sauter's quadrature rule on quadrangular mesh. It handles various cases including same panel, common edge, common vertex and regular cell neighboring types.
Parameters
kernel_function Laplace kernel function.
kx_cell_iter Iterator pointing to $K_x$.
kx_cell_iter Iterator pointing to $K_y$.
kx_mapping Mapping used for $K_x$. Because a mesher usually generates 1st order grid, if there is no additional manifold specification, the mapping should be 1st order.
kx_mapping Mapping used for $K_y$. Because a mesher usually generates 1st order grid, if there is no additional manifold specification, the mapping should be 1st order.
References LaplaceBEM::hierarchical_support_points_in_real_cell(), and LaplaceBEM::SauterQuadRule().
SauterQuadRule() [3/3]
template<int dim, int spacedim, typename RangeNumberType = double> void LaplaceBEM::SauterQuadRule (FullMatrix< RangeNumberType > & system_matrix, const LaplaceKernel::KernelFunction< spacedim, RangeNumberType > & kernel_function, const BEMValues< dim, spacedim > & bem_values, const typename DoFHandler< dim, spacedim >::cell_iterator & kx_cell_iter, const typename DoFHandler< dim, spacedim >::cell_iterator & ky_cell_iter, const MappingQGeneric< dim, spacedim > & kx_mapping = MappingQGeneric<dim, spacedim>(1), const MappingQGeneric< dim, spacedim > & ky_mapping = MappingQGeneric<dim, spacedim>(1))
This function implements Sauter's quadrature rule on quadrangular mesh. It handles various cases including same panel, common edge, common vertex and regular cell neighboring types.
Parameters
kernel_function Laplace kernel function.
kx_cell_iter Iterator pointing to $K_x$.
kx_cell_iter Iterator pointing to $K_y$.
kx_mapping Mapping used for $K_x$. Because a mesher usually generates 1st order grid, if there is no additional manifold specification, the mapping should be 1st order.
kx_mapping Mapping used for $K_y$. Because a mesher usually generates 1st order grid, if there is no additional manifold specification, the mapping should be 1st order.
References LaplaceBEM::hierarchical_support_points_in_real_cell(), and LaplaceBEM::SauterQuadRule().
surface_jacobian_det() [1/2]
template<int dim, int spacedim> double LaplaceBEM::surface_jacobian_det (const FiniteElement< dim, spacedim > & fe, const std::vector< Point< spacedim >> & support_points_in_real_cell, const Point< dim > & p)
Calculate the surface Jacobian determinant at specified area coordinates. Shape functions and support points in the real cell have been reordered to the tensor product ordering before the calculation.
References LaplaceBEM::surface_jacobian_det().
Referenced by LaplaceBEM::surface_jacobian_det().
surface_jacobian_det() [2/2]
template<int spacedim> double LaplaceBEM::surface_jacobian_det (const unsigned int k3_index, const unsigned int quad_no, const Table< 2, FullMatrix< double >> & shape_grad_matrix_table, const std::vector< Point< spacedim >> & support_points_in_real_cell)
Calculate the surface Jacobian determinant at specified area coordinates. Shape functions and support points in the real cell have been reordered to the tensor product ordering before the calculation.
References LaplaceBEM::surface_jacobian_det().
transform_unit_to_permuted_real_cell() [1/2]
template<int dim, int spacedim> Point<spacedim> LaplaceBEM::transform_unit_to_permuted_real_cell (const FiniteElement< dim, spacedim > & fe, const std::vector< Point< spacedim >> & support_points_in_real_cell, const Point< dim > & area_coords)
Calculate the coordinate transformation from a unit cell to real cell for Qp element.
Parameters
fe
support_points_in_real_cell coordinates of the support points in the real cell, which are in the tensor product order.
area_coords
Returns
References LaplaceBEM::transform_unit_to_permuted_real_cell().
Referenced by LaplaceBEM::transform_unit_to_permuted_real_cell(), and LaplaceBEM::KernelPulledbackToUnitCell< dim, spacedim, RangeNumberType >::value().
transform_unit_to_permuted_real_cell() [2/2]
template<int spacedim> Point<spacedim> LaplaceBEM::transform_unit_to_permuted_real_cell (const unsigned int k3_index, const unsigned int quad_no, const Table< 3, double > & shape_value_table, const std::vector< Point< spacedim >> & support_points_in_real_cell)
Calculate the coordinate transformation from a unit cell to real cell for Qp element.
Parameters
k3_index
quad_no
shape_value_table
support_points_in_real_cell coordinates of the support points in the real cell, which are in the tensor product order.
Returns
References LaplaceBEM::transform_unit_to_permuted_real_cell().